/**
 * RETRATOS REALES DEL REPARTO, CON LICENCIA VERIFICADA.
 *
 * FICHERO GENERADO — no editar a mano.
 *   node scripts/barrer-commons.mjs --bajar
 *   node scripts/optimizar-medios.mjs
 *   node scripts/generar-manifiesto-commons.mjs
 *
 * Cada entrada es una fotografía real de un intérprete de la serie que estaba en Wikimedia
 * Commons bajo una licencia de la lista blanca. De cada una se comprobó la licencia con la
 * API antes de descargarla, y su atribución viaja aquí pegada porque las CC BY y CC BY-SA
 * obligan a citar: son gratis citando, no gratis.
 *
 * Lo que NO hay aquí, y no es un descuido: fotogramas, promocionales, carteles y el logotipo
 * de la serie. Ese material tiene dueño y no se publica sin permiso. Sus huecos están
 * declarados en `huecos.ts` esperando, con arte propio detrás mientras tanto.
 *
 * Generado el 2026-08-16 · 23 retratos.
 */

import type { MediaAsset } from '@/domain/media/tipos';

export const RETRATOS_COMMONS: readonly MediaAsset[] = [
  {
    id: 'commons:loles-leon',
    type: 'image',
    category: 'character',
    title: 'Loles León en la alfombra roja de los Premios Goya celebrados en Sevilla en Febrero 2019',
    localPath: '/media/licensed/loles-leon.webp',
    miniPath: '/media/licensed/loles-leon-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Loles_Leon.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Loles_Leon.jpg',
    characters: ['Paloma Hurtado'],
    interprete: 'Loles León',
    tags: ['personaje', 'reparto', 'loles león'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:loles-leon-2',
    type: 'image',
    category: 'character',
    title: 'Loles León en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid',
    localPath: '/media/licensed/loles-leon-2.webp',
    miniPath: '/media/licensed/loles-leon-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Loles_Le%C3%B3n.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Loles_Le%C3%B3n.jpg',
    characters: ['Paloma Hurtado'],
    interprete: 'Loles León',
    tags: ['personaje', 'reparto', 'loles león'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:fernando-tejero',
    type: 'image',
    category: 'character',
    title: 'Fernando Tejero en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid',
    localPath: '/media/licensed/fernando-tejero.webp',
    miniPath: '/media/licensed/fernando-tejero-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Fernando_Tejero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Fernando_Tejero.jpg',
    characters: ['Emilio Delgado'],
    interprete: 'Fernando Tejero',
    tags: ['personaje', 'reparto', 'fernando tejero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:fernando-tejero-2',
    type: 'image',
    category: 'character',
    title: 'Fernando Tejero en la alfombra roja de la ceremonia de entrega de los Premios Goya 2020 celebrada en Málaga',
    localPath: '/media/licensed/fernando-tejero-2.webp',
    miniPath: '/media/licensed/fernando-tejero-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2020_-_Fernando_Tejero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2020_-_Fernando_Tejero.jpg',
    characters: ['Emilio Delgado'],
    interprete: 'Fernando Tejero',
    tags: ['personaje', 'reparto', 'fernando tejero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:malena-alterio',
    type: 'image',
    category: 'character',
    title: 'Malena Alterio en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid Fecha',
    localPath: '/media/licensed/malena-alterio.webp',
    miniPath: '/media/licensed/malena-alterio-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Malena_Alterio_01.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Malena_Alterio_01.jpg',
    characters: ['Belén López Vázquez'],
    interprete: 'Malena Alterio',
    tags: ['personaje', 'reparto', 'malena alterio'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:malena-alterio-2',
    type: 'image',
    category: 'character',
    title: 'Malena Alterio on the red carpet of the Goya Awards held in Granada in 2025',
    localPath: '/media/licensed/malena-alterio-2.webp',
    miniPath: '/media/licensed/malena-alterio-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2025_-_Malena_Alterio.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2025_-_Malena_Alterio.jpg',
    characters: ['Belén López Vázquez'],
    interprete: 'Malena Alterio',
    tags: ['personaje', 'reparto', 'malena alterio'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:laura-pamplona',
    type: 'image',
    category: 'character',
    title: 'Fotos del photocall y fiesta de lanzamiento de un nuevo canal de televisión en España.',
    localPath: '/media/licensed/laura-pamplona.webp',
    miniPath: '/media/licensed/laura-pamplona-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Laura_Pamplona._(21025776203).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Laura_Pamplona._(21025776203).jpg',
    characters: ['Alicia Sanz'],
    interprete: 'Laura Pamplona',
    tags: ['personaje', 'reparto', 'laura pamplona'],
    usageStatus: 'licensed',
    license: 'CC0',
    attribution: 'Foto: Non Stop People · CC0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:laura-pamplona-2',
    type: 'image',
    category: 'character',
    title: 'La actriz española LAURA PAMPLONA en 2015.',
    localPath: '/media/licensed/laura-pamplona-2.webp',
    miniPath: '/media/licensed/laura-pamplona-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Laura_Pamplona_2015.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Laura_Pamplona_2015.jpg',
    characters: ['Alicia Sanz'],
    interprete: 'Laura Pamplona',
    tags: ['personaje', 'reparto', 'laura pamplona'],
    usageStatus: 'licensed',
    license: 'CC0',
    attribution: 'Foto: Non Stop People · CC0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:maria-adanez',
    type: 'image',
    category: 'character',
    title: 'Maria Adanez en la alfombra roja de los Premios Goya celebrados en Sevilla en Febrero 2019',
    localPath: '/media/licensed/maria-adanez.webp',
    miniPath: '/media/licensed/maria-adanez-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Maria_Adanez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Maria_Adanez.jpg',
    characters: ['Lucía Álvarez'],
    interprete: 'María Adánez',
    tags: ['personaje', 'reparto', 'maría adánez'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:maria-adanez-2',
    type: 'image',
    category: 'character',
    title: 'María Adánez en la alfombra roja del Festival de Málaga 2024 frente al Teatro Cervantes',
    localPath: '/media/licensed/maria-adanez-2.webp',
    miniPath: '/media/licensed/maria-adanez-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Mar%C3%ADa_Ad%C3%A1nez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Mar%C3%ADa_Ad%C3%A1nez.jpg',
    characters: ['Lucía Álvarez'],
    interprete: 'María Adánez',
    tags: ['personaje', 'reparto', 'maría adánez'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:gemma-cuervo',
    type: 'image',
    category: 'character',
    title: 'Gemma Cuervo, Spanish actress, circa 1975',
    localPath: '/media/licensed/gemma-cuervo.webp',
    miniPath: '/media/licensed/gemma-cuervo-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Gemma_Cuervo_(1975).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Gemma_Cuervo_(1975).jpg',
    characters: ['Vicenta Benito'],
    interprete: 'Gemma Cuervo',
    tags: ['personaje', 'reparto', 'gemma cuervo'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Desconocido · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:emma-penella',
    type: 'image',
    category: 'character',
    title: 'Emma Penella posa para las fotos promocionarles del último trabajo en el que participó la actriz madrileña.',
    localPath: '/media/licensed/emma-penella.webp',
    miniPath: '/media/licensed/emma-penella-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Emma_Penella_posa_en_las_fotos_promocionales_de_%27La_que_se_avecina%27.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Emma_Penella_posa_en_las_fotos_promocionales_de_%27La_que_se_avecina%27.jpg',
    characters: ['Concha'],
    interprete: 'Emma Penella',
    tags: ['personaje', 'reparto', 'emma penella'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ayoamaro · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:isabel-ordaz',
    type: 'image',
    category: 'character',
    title: 'Seminci 2016',
    localPath: '/media/licensed/isabel-ordaz.webp',
    miniPath: '/media/licensed/isabel-ordaz-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Isabel_Ordaz_-_Seminci_2016.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Isabel_Ordaz_-_Seminci_2016.jpg',
    characters: ['Isabel Ruiz'],
    interprete: 'Isabel Ordaz',
    tags: ['personaje', 'reparto', 'isabel ordaz'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:isabel-ordaz-2',
    type: 'image',
    category: 'character',
    title: 'Isabel Ordaz',
    localPath: '/media/licensed/isabel-ordaz-2.webp',
    miniPath: '/media/licensed/isabel-ordaz-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Isabel-ordaz.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Isabel-ordaz.jpg',
    characters: ['Isabel Ruiz'],
    interprete: 'Isabel Ordaz',
    tags: ['personaje', 'reparto', 'isabel ordaz'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Terrigena · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eva-isanta',
    type: 'image',
    category: 'character',
    title: 'Seminci 2016',
    localPath: '/media/licensed/eva-isanta.webp',
    miniPath: '/media/licensed/eva-isanta-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Eva_Isanta_-_Seminci_2016.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Eva_Isanta_-_Seminci_2016.jpg',
    characters: ['Bea Villarejo'],
    interprete: 'Eva Isanta',
    tags: ['personaje', 'reparto', 'eva isanta'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eva-isanta-2',
    type: 'image',
    category: 'character',
    title: 'Seminci 2016',
    localPath: '/media/licensed/eva-isanta-2.webp',
    miniPath: '/media/licensed/eva-isanta-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Eva_Isanta_(cropped).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Eva_Isanta_(cropped).jpg',
    characters: ['Bea Villarejo'],
    interprete: 'Eva Isanta',
    tags: ['personaje', 'reparto', 'eva isanta'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:beatriz-carvajal-2',
    type: 'image',
    category: 'character',
    title: 'Spanish Actress Beatriz Carvajal',
    localPath: '/media/licensed/beatriz-carvajal-2.webp',
    miniPath: '/media/licensed/beatriz-carvajal-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carvajal2013.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Carvajal2013.jpg',
    characters: ['María Jesús Vázquez'],
    interprete: 'Beatriz Carvajal',
    tags: ['personaje', 'reparto', 'beatriz carvajal'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: https://www.youtube.com/channel/UClfP9MtgkBtOIuzQRjLmyXg Ángel Galán Comunicación (youtube) · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:vanesa-romero',
    type: 'image',
    category: 'character',
    title: 'Vanesa Romero at Red Carpet of Goya Awards 2026 in Barcelona',
    localPath: '/media/licensed/vanesa-romero.webp',
    miniPath: '/media/licensed/vanesa-romero-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026_-_Vanesa_Romero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026_-_Vanesa_Romero.jpg',
    characters: ['Ana'],
    interprete: 'Vanesa Romero',
    tags: ['personaje', 'reparto', 'vanesa romero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:vanesa-romero-2',
    type: 'image',
    category: 'character',
    title: 'Vanesa Romero en la alfombra roja del Festival de Málaga 2024 frente al Teatro Cervantes',
    localPath: '/media/licensed/vanesa-romero-2.webp',
    miniPath: '/media/licensed/vanesa-romero-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Vanesa_Romero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Vanesa_Romero.jpg',
    characters: ['Ana'],
    interprete: 'Vanesa Romero',
    tags: ['personaje', 'reparto', 'vanesa romero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:carmen-balague',
    type: 'image',
    category: 'character',
    title: 'Las actrices Imma Colomer, Rosa Gàmiz y Carme Balagué en el estreno de la película Fènix 11:23.',
    localPath: '/media/licensed/carmen-balague.webp',
    miniPath: '/media/licensed/carmen-balague-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carmen_Balagu%C3%A9_Colomer-G%C3%A0miz-Balagu%C3%A9_(cropped).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Carmen_Balagu%C3%A9_Colomer-G%C3%A0miz-Balagu%C3%A9_(cropped).jpg',
    characters: ['Nieves Cuesta'],
    interprete: 'Carmen Balagué',
    tags: ['personaje', 'reparto', 'carmen balagué'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Moritz Barcelona/Oriol Miralles · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:cristina-castano',
    type: 'image',
    category: 'character',
    title: 'Premios Goya 2017',
    localPath: '/media/licensed/cristina-castano.webp',
    miniPath: '/media/licensed/cristina-castano-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cristina_Casta%C3%B1o_en_los_Premios_Goya_2017.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Cristina_Casta%C3%B1o_en_los_Premios_Goya_2017.jpg',
    characters: ['Bea'],
    interprete: 'Cristina Castaño',
    tags: ['personaje', 'reparto', 'cristina castaño'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:cristina-castano-2',
    type: 'image',
    category: 'character',
    title: 'Cristina Castaño en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid',
    localPath: '/media/licensed/cristina-castano-2.webp',
    miniPath: '/media/licensed/cristina-castano-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Cristina_Casta%C3%B1o.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Cristina_Casta%C3%B1o.jpg',
    characters: ['Bea'],
    interprete: 'Cristina Castaño',
    tags: ['personaje', 'reparto', 'cristina castaño'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:emilio-gutierrez-caba-2',
    type: 'image',
    category: 'character',
    title: 'Emilio Gutiérrez Caba at Red Carpet of Goya Awards 2026 in Barcelona',
    localPath: '/media/licensed/emilio-gutierrez-caba-2.webp',
    miniPath: '/media/licensed/emilio-gutierrez-caba-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026-_Emilio_Guti%C3%A9rrez_Caba.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026-_Emilio_Guti%C3%A9rrez_Caba.jpg',
    characters: ['Padre de Juan'],
    interprete: 'Emilio Gutiérrez Caba',
    tags: ['personaje', 'reparto', 'emilio gutiérrez caba'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
];
