/**
 * RETRATOS REALES DEL REPARTO, CON LICENCIA VERIFICADA.
 *
 * FICHERO GENERADO — no editar a mano.
 *   node scripts/barrer-commons.mjs --bajar
 *   node scripts/optimizar-medios.mjs
 *   node scripts/generar-manifiesto-commons.mjs
 *
 * Cada entrada es una fotografía real de un intérprete de la serie que estaba en Wikimedia
 * Commons bajo una licencia de la lista blanca. De cada una se comprobó la licencia con la
 * API antes de descargarla, y su atribución viaja aquí pegada porque las CC BY y CC BY-SA
 * obligan a citar: son gratis citando, no gratis.
 *
 * Lo que NO hay aquí, y no es un descuido: fotogramas, promocionales, carteles y el logotipo
 * de la serie. Ese material tiene dueño y no se publica sin permiso. Sus huecos están
 * declarados en `huecos.ts` esperando, con arte propio detrás mientras tanto.
 *
 * Generado el 2026-08-15 · 55 retratos.
 */

import type { MediaAsset } from '@/domain/media/tipos';

export const RETRATOS_COMMONS: readonly MediaAsset[] = [
  {
    id: 'commons:jose-luis-gil',
    type: 'image',
    category: 'character',
    title: 'Spanish Actor José Luis Gil.',
    localPath: '/media/licensed/jose-luis-gil.webp',
    miniPath: '/media/licensed/jose-luis-gil-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Luis_Gil_2016.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Luis_Gil_2016.jpg',
    characters: ['Juan Cuesta'],
    interprete: 'José Luis Gil',
    tags: ['personaje', 'reparto', 'josé luis gil'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 2.0',
    attribution: 'Foto: Festival Internacional de Teatro Clásico de Almagro · CC BY-SA 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:jose-luis-gil-2',
    type: 'image',
    category: 'character',
    title: 'Jose Luis Gil (University of Cantabria, Spain) at the 6th World Water Forum',
    localPath: '/media/licensed/jose-luis-gil-2.webp',
    miniPath: '/media/licensed/jose-luis-gil-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Jose_Luis_Gil-IMG_4126.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Jose_Luis_Gil-IMG_4126.jpg',
    characters: ['Juan Cuesta'],
    interprete: 'José Luis Gil',
    tags: ['personaje', 'reparto', 'josé luis gil'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 2.0 fr',
    attribution: 'Foto: Rama · CC BY-SA 2.0 fr · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:loles-leon',
    type: 'image',
    category: 'character',
    title: 'Loles León en la alfombra roja de los Premios Goya celebrados en Sevilla en Febrero 2019',
    localPath: '/media/licensed/loles-leon.webp',
    miniPath: '/media/licensed/loles-leon-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Loles_Leon.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Loles_Leon.jpg',
    characters: ['Paloma Hurtado'],
    interprete: 'Loles León',
    tags: ['personaje', 'reparto', 'loles león'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:loles-leon-2',
    type: 'image',
    category: 'character',
    title: 'Loles León en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid',
    localPath: '/media/licensed/loles-leon-2.webp',
    miniPath: '/media/licensed/loles-leon-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Loles_Le%C3%B3n.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Loles_Le%C3%B3n.jpg',
    characters: ['Paloma Hurtado'],
    interprete: 'Loles León',
    tags: ['personaje', 'reparto', 'loles león'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:sofia-nieto',
    type: 'image',
    category: 'character',
    title: '_AG_7094',
    localPath: '/media/licensed/sofia-nieto.webp',
    miniPath: '/media/licensed/sofia-nieto-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Enrique_Pe%C3%B1a_Nieto_and_family_voting_in_the_2018_General_Election_-_AG_7094_(42258306325).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Enrique_Pe%C3%B1a_Nieto_and_family_voting_in_the_2018_General_Election_-_AG_7094_(42258306325).jpg',
    characters: ['Natalia Cuesta'],
    interprete: 'Sofía Nieto',
    tags: ['personaje', 'reparto', 'sofía nieto'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Presidencia de la República Mexicana · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:sofia-nieto-2',
    type: 'image',
    category: 'character',
    title: '_AG_6970',
    localPath: '/media/licensed/sofia-nieto-2.webp',
    miniPath: '/media/licensed/sofia-nieto-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Enrique_Pe%C3%B1a_Nieto_and_family_voting_in_the_2018_General_Election_-_AG_6970_(43112863222).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Enrique_Pe%C3%B1a_Nieto_and_family_voting_in_the_2018_General_Election_-_AG_6970_(43112863222).jpg',
    characters: ['Natalia Cuesta'],
    interprete: 'Sofía Nieto',
    tags: ['personaje', 'reparto', 'sofía nieto'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Presidencia de la República Mexicana · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eduardo-garcia',
    type: 'image',
    category: 'character',
    title: 'Tumba de Eduardo García López y Felisa Melendo Alonso-Magadán, en el cementerio civil de Madrid.',
    localPath: '/media/licensed/eduardo-garcia.webp',
    miniPath: '/media/licensed/eduardo-garcia-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tumba_de_Eduardo_Garc%C3%ADa_L%C3%B3pez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Tumba_de_Eduardo_Garc%C3%ADa_L%C3%B3pez.jpg',
    characters: ['José Miguel Cuesta'],
    interprete: 'Eduardo García',
    tags: ['personaje', 'reparto', 'eduardo garcía'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Strakhov · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eduardo-garcia-2',
    type: 'image',
    category: 'character',
    title: 'Das Grab des spanischen kommunistischen Politikers Eduardo García López auf dem Cemnterio Civile in Madrid.',
    localPath: '/media/licensed/eduardo-garcia-2.webp',
    miniPath: '/media/licensed/eduardo-garcia-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Grab_Eduardo_Garc%C3%ADa_L%C3%B3pez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Grab_Eduardo_Garc%C3%ADa_L%C3%B3pez.jpg',
    characters: ['José Miguel Cuesta'],
    interprete: 'Eduardo García',
    tags: ['personaje', 'reparto', 'eduardo garcía'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Harvey Kneeslapper · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:fernando-tejero',
    type: 'image',
    category: 'character',
    title: 'Fernando Tejero en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid',
    localPath: '/media/licensed/fernando-tejero.webp',
    miniPath: '/media/licensed/fernando-tejero-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Fernando_Tejero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Fernando_Tejero.jpg',
    characters: ['Emilio Delgado'],
    interprete: 'Fernando Tejero',
    tags: ['personaje', 'reparto', 'fernando tejero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:fernando-tejero-2',
    type: 'image',
    category: 'character',
    title: 'Fernando Tejero en la alfombra roja de la ceremonia de entrega de los Premios Goya 2020 celebrada en Málaga',
    localPath: '/media/licensed/fernando-tejero-2.webp',
    miniPath: '/media/licensed/fernando-tejero-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2020_-_Fernando_Tejero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2020_-_Fernando_Tejero.jpg',
    characters: ['Emilio Delgado'],
    interprete: 'Fernando Tejero',
    tags: ['personaje', 'reparto', 'fernando tejero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eduardo-gomez',
    type: 'image',
    category: 'character',
    title: 'Eduardo Gómez',
    localPath: '/media/licensed/eduardo-gomez.webp',
    miniPath: '/media/licensed/eduardo-gomez-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Eduardo_G%C3%B3mez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Eduardo_G%C3%B3mez.jpg',
    characters: ['Mariano Delgado'],
    interprete: 'Eduardo Gómez',
    tags: ['personaje', 'reparto', 'eduardo gómez'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Gabrielicus · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eduardo-gomez-2',
    type: 'image',
    category: 'character',
    title: 'Eduardo Gómez (Publ)',
    localPath: '/media/licensed/eduardo-gomez-2.webp',
    miniPath: '/media/licensed/eduardo-gomez-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:1918-08-01,_Espa%C3%B1a_M%C3%A9dica,_Eduardo_G._Gereda.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:1918-08-01,_Espa%C3%B1a_M%C3%A9dica,_Eduardo_G._Gereda.jpg',
    characters: ['Mariano Delgado'],
    interprete: 'Eduardo Gómez',
    tags: ['personaje', 'reparto', 'eduardo gómez'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Not stated. Unknown. · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:malena-alterio',
    type: 'image',
    category: 'character',
    title: 'Malena Alterio en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid Fecha',
    localPath: '/media/licensed/malena-alterio.webp',
    miniPath: '/media/licensed/malena-alterio-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Malena_Alterio_01.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Malena_Alterio_01.jpg',
    characters: ['Belén López Vázquez'],
    interprete: 'Malena Alterio',
    tags: ['personaje', 'reparto', 'malena alterio'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:malena-alterio-2',
    type: 'image',
    category: 'character',
    title: 'Malena Alterio on the red carpet of the Goya Awards held in Granada in 2025',
    localPath: '/media/licensed/malena-alterio-2.webp',
    miniPath: '/media/licensed/malena-alterio-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2025_-_Malena_Alterio.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2025_-_Malena_Alterio.jpg',
    characters: ['Belén López Vázquez'],
    interprete: 'Malena Alterio',
    tags: ['personaje', 'reparto', 'malena alterio'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:laura-pamplona',
    type: 'image',
    category: 'character',
    title: 'Laura Pamplona (2024)',
    localPath: '/media/licensed/laura-pamplona.webp',
    miniPath: '/media/licensed/laura-pamplona-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ciudadela-poternas_3.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Ciudadela-poternas_3.jpg',
    characters: ['Alicia Sanz'],
    interprete: 'Laura Pamplona',
    tags: ['personaje', 'reparto', 'laura pamplona'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: JLVwiki · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:laura-pamplona-2',
    type: 'image',
    category: 'character',
    title: 'The Laura at George\'s Island in July 2010',
    localPath: '/media/licensed/laura-pamplona-2.webp',
    miniPath: '/media/licensed/laura-pamplona-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Laura_at_George%27s_Island,_July_2010.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Laura_at_George%27s_Island,_July_2010.jpg',
    characters: ['Alicia Sanz'],
    interprete: 'Laura Pamplona',
    tags: ['personaje', 'reparto', 'laura pamplona'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Vitor Pamplona from Cambridge, MA, USA · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:maria-adanez',
    type: 'image',
    category: 'character',
    title: 'Maria Adanez en la alfombra roja de los Premios Goya celebrados en Sevilla en Febrero 2019',
    localPath: '/media/licensed/maria-adanez.webp',
    miniPath: '/media/licensed/maria-adanez-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Maria_Adanez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2019_-_Maria_Adanez.jpg',
    characters: ['Lucía Álvarez'],
    interprete: 'María Adánez',
    tags: ['personaje', 'reparto', 'maría adánez'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:maria-adanez-2',
    type: 'image',
    category: 'character',
    title: 'María Adánez en la alfombra roja del Festival de Málaga 2024 frente al Teatro Cervantes',
    localPath: '/media/licensed/maria-adanez-2.webp',
    miniPath: '/media/licensed/maria-adanez-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Mar%C3%ADa_Ad%C3%A1nez.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Mar%C3%ADa_Ad%C3%A1nez.jpg',
    characters: ['Lucía Álvarez'],
    interprete: 'María Adánez',
    tags: ['personaje', 'reparto', 'maría adánez'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:daniel-guzman',
    type: 'image',
    category: 'character',
    title: 'Daniel Guzmán',
    localPath: '/media/licensed/daniel-guzman.webp',
    miniPath: '/media/licensed/daniel-guzman-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Block_book_of_the_County_of_St._Louis_(Volume_1)_(Book_4)_Page_37_(Daniel_G._Taylor%27s_Sub._Of_Lots_5,_6,_%26_7_in_Hunt%27s_Add.)_-_DPLA_-_070a148e02827fc3d130ffd455dd9dc2.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Block_book_of_the_County_of_St._Louis_(Volume_1)_(Book_4)_Page_37_(Daniel_G._Taylor%27s_Sub._Of_Lots_5,_6,_%26_7_in_Hunt%27s_Add.)_-_DPLA_-_070a148e02827fc3d130ffd455dd9dc2.jpg',
    characters: ['Roberto Alonso'],
    interprete: 'Daniel Guzmán',
    tags: ['personaje', 'reparto', 'daniel guzmán'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Guzman, Ignatz P · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:daniel-guzman-2',
    type: 'image',
    category: 'character',
    title: 'Daniel Guzmán (2023)',
    localPath: '/media/licensed/daniel-guzman-2.webp',
    miniPath: '/media/licensed/daniel-guzman-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fabulosos_Cadillacs_at_Z%C3%B3calo,_2023_(52951893461).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Fabulosos_Cadillacs_at_Z%C3%B3calo,_2023_(52951893461).jpg',
    characters: ['Roberto Alonso'],
    interprete: 'Daniel Guzmán',
    tags: ['personaje', 'reparto', 'daniel guzmán'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Secretaría de Cultura de la Ciudad de México from México · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:luis-merlo',
    type: 'image',
    category: 'character',
    title: 'water',
    localPath: '/media/licensed/luis-merlo.webp',
    miniPath: '/media/licensed/luis-merlo-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroyo_Merlo_San_Luis.JPG',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Arroyo_Merlo_San_Luis.JPG',
    characters: ['Mauri Hidalgo'],
    interprete: 'Luis Merlo',
    tags: ['personaje', 'reparto', 'luis merlo'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Gabriel fgm · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:luis-merlo-2',
    type: 'image',
    category: 'character',
    title: 'This is a photo of an Argentine monument identified by the ID',
    localPath: '/media/licensed/luis-merlo-2.webp',
    miniPath: '/media/licensed/luis-merlo-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Iglesia_Hist%C3%B3rica_%22Nuestra_Se%C3%B1ora_del_Rosario%22_-_Merlo_-_San_Luis.JPG',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Iglesia_Hist%C3%B3rica_%22Nuestra_Se%C3%B1ora_del_Rosario%22_-_Merlo_-_San_Luis.JPG',
    characters: ['Mauri Hidalgo'],
    interprete: 'Luis Merlo',
    tags: ['personaje', 'reparto', 'luis merlo'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: Carina L. Staiti · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:adria-collado',
    type: 'image',
    category: 'character',
    title: 'Vista del Rio Besós desde el puente más antiguo de Sant Adrià de Besòs.',
    localPath: '/media/licensed/adria-collado.webp',
    miniPath: '/media/licensed/adria-collado-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rbesos01.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Rbesos01.jpg',
    characters: ['Fernando Navarro'],
    interprete: 'Adrià Collado',
    tags: ['personaje', 'reparto', 'adrià collado'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: José Luis Moncada Collado · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:adria-collado-2',
    type: 'image',
    category: 'character',
    title: 'Río Besòs a su paso por Sant Adrià de Besos , dirección mar, a menos de un km de la desembocadura',
    localPath: '/media/licensed/adria-collado-2.webp',
    miniPath: '/media/licensed/adria-collado-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rbesos02.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Rbesos02.jpg',
    characters: ['Fernando Navarro'],
    interprete: 'Adrià Collado',
    tags: ['personaje', 'reparto', 'adrià collado'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: José Luis Moncada Collado · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:marivi-bilbao',
    type: 'image',
    category: 'character',
    title: 'Mariví Bilbao in the International Huesca Film Festival (14/06/08).',
    localPath: '/media/licensed/marivi-bilbao.webp',
    miniPath: '/media/licensed/marivi-bilbao-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Marivi_Bilbao.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Marivi_Bilbao.jpg',
    characters: ['Marisa Benito'],
    interprete: 'Mariví Bilbao',
    tags: ['personaje', 'reparto', 'mariví bilbao'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Tgenerelo · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:gemma-cuervo',
    type: 'image',
    category: 'character',
    title: 'Gemma Cuervo, Spanish actress, circa 1975',
    localPath: '/media/licensed/gemma-cuervo.webp',
    miniPath: '/media/licensed/gemma-cuervo-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Gemma_Cuervo_(1975).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Gemma_Cuervo_(1975).jpg',
    characters: ['Vicenta Benito'],
    interprete: 'Gemma Cuervo',
    tags: ['personaje', 'reparto', 'gemma cuervo'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Desconocido · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:emma-penella',
    type: 'image',
    category: 'character',
    title: 'Emma Penella posa para las fotos promocionarles del último trabajo en el que participó la actriz madrileña.',
    localPath: '/media/licensed/emma-penella.webp',
    miniPath: '/media/licensed/emma-penella-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Emma_Penella_posa_en_las_fotos_promocionales_de_%27La_que_se_avecina%27.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Emma_Penella_posa_en_las_fotos_promocionales_de_%27La_que_se_avecina%27.jpg',
    characters: ['Concha'],
    interprete: 'Emma Penella',
    tags: ['personaje', 'reparto', 'emma penella'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ayoamaro · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:isabel-ordaz',
    type: 'image',
    category: 'character',
    title: 'Seminci 2016',
    localPath: '/media/licensed/isabel-ordaz.webp',
    miniPath: '/media/licensed/isabel-ordaz-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Isabel_Ordaz_-_Seminci_2016.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Isabel_Ordaz_-_Seminci_2016.jpg',
    characters: ['Isabel Ruiz'],
    interprete: 'Isabel Ordaz',
    tags: ['personaje', 'reparto', 'isabel ordaz'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:isabel-ordaz-2',
    type: 'image',
    category: 'character',
    title: 'Isabel Ordaz (2008)',
    localPath: '/media/licensed/isabel-ordaz-2.webp',
    miniPath: '/media/licensed/isabel-ordaz-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Y_el_ni%C3%B1o_qu%C3%A9_se_me_hizo%3F_(3096721136).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Y_el_ni%C3%B1o_qu%C3%A9_se_me_hizo%3F_(3096721136).jpg',
    characters: ['Isabel Ruiz'],
    interprete: 'Isabel Ordaz',
    tags: ['personaje', 'reparto', 'isabel ordaz'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Gabriel S. Delgado C. from Puerto Ordaz, Venezuela · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:santiago-ramos',
    type: 'image',
    category: 'character',
    title: 'Praia (Cap-Vert) : Liceu Domingos Ramos (en travaux)',
    localPath: '/media/licensed/santiago-ramos.webp',
    miniPath: '/media/licensed/santiago-ramos-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Praia-Liceu_Domingos_Ramos_(2).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Praia-Liceu_Domingos_Ramos_(2).jpg',
    characters: ['Andrés Guerra'],
    interprete: 'Santiago Ramos',
    tags: ['personaje', 'reparto', 'santiago ramos'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: Ji-Elle · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:santiago-ramos-2',
    type: 'image',
    category: 'character',
    title: 'Praia (Cap-Vert) : Liceu Domingos Ramos (en travaux)',
    localPath: '/media/licensed/santiago-ramos-2.webp',
    miniPath: '/media/licensed/santiago-ramos-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Praia-Liceu_Domingos_Ramos_(3).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Praia-Liceu_Domingos_Ramos_(3).jpg',
    characters: ['Andrés Guerra'],
    interprete: 'Santiago Ramos',
    tags: ['personaje', 'reparto', 'santiago ramos'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: Ji-Elle · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:elio-gonzalez',
    type: 'image',
    category: 'character',
    title: 'Spanish Politician Francisco Javier González de Castejón y Elío',
    localPath: '/media/licensed/elio-gonzalez.webp',
    miniPath: '/media/licensed/elio-gonzalez-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Gonz%C3%A1lez_de_El%C3%ADo.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Gonz%C3%A1lez_de_El%C3%ADo.jpg',
    characters: ['Pablo Guerra'],
    interprete: 'Elio González',
    tags: ['personaje', 'reparto', 'elio gonzález'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: Unknown authorUnknown author · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:guillermo-ortega',
    type: 'image',
    category: 'character',
    title: 'Guillermo Ortega (2013)',
    localPath: '/media/licensed/guillermo-ortega.webp',
    miniPath: '/media/licensed/guillermo-ortega-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:MuralMetroTacubya04.JPG',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:MuralMetroTacubya04.JPG',
    characters: ['Álex Guerra', 'Paco'],
    interprete: 'Guillermo Ortega',
    tags: ['personaje', 'reparto', 'guillermo ortega'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: AlejandroLinaresGarcia · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:guillermo-ortega-2',
    type: 'image',
    category: 'character',
    title: 'Guillermo León Valencia',
    localPath: '/media/licensed/guillermo-ortega-2.webp',
    miniPath: '/media/licensed/guillermo-ortega-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Guillermo_Le%C3%B3n_Valencia_1a.JPG',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Guillermo_Le%C3%B3n_Valencia_1a.JPG',
    characters: ['Álex Guerra', 'Paco'],
    interprete: 'Guillermo Ortega',
    tags: ['personaje', 'reparto', 'guillermo ortega'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Julian David Muñoz Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:mariano-alameda',
    type: 'image',
    category: 'character',
    title: 'Near Alameda de Santa María, Mexico City',
    localPath: '/media/licensed/mariano-alameda.webp',
    miniPath: '/media/licensed/mariano-alameda-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wikimania15_Dschwen_(111).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Wikimania15_Dschwen_(111).jpg',
    characters: ['Armando Ruiz'],
    interprete: 'Mariano Alameda',
    tags: ['personaje', 'reparto', 'mariano alameda'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: dschwen · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:mariano-alameda-2',
    type: 'image',
    category: 'character',
    title: 'Mariano Alameda (2021)',
    localPath: '/media/licensed/mariano-alameda-2.webp',
    miniPath: '/media/licensed/mariano-alameda-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ministry_of_Foreign_Affairs_(01815700)_(51325547094).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Ministry_of_Foreign_Affairs_(01815700)_(51325547094).jpg',
    characters: ['Armando Ruiz'],
    interprete: 'Mariano Alameda',
    tags: ['personaje', 'reparto', 'mariano alameda'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: IAEA Imagebank · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:nathalie-sesena',
    type: 'image',
    category: 'character',
    title: 'Spanish actress Nathalie Seseña',
    localPath: '/media/licensed/nathalie-sesena.webp',
    miniPath: '/media/licensed/nathalie-sesena-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nathalie_Sese%C3%B1a.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Nathalie_Sese%C3%B1a.jpg',
    characters: ['Marisa Benito (joven)'],
    interprete: 'Nathalie Seseña',
    tags: ['personaje', 'reparto', 'nathalie seseña'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 3.0',
    attribution: 'Foto: 20minutos.es · CC BY-SA 3.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eva-isanta',
    type: 'image',
    category: 'character',
    title: 'Seminci 2016',
    localPath: '/media/licensed/eva-isanta.webp',
    miniPath: '/media/licensed/eva-isanta-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Eva_Isanta_-_Seminci_2016.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Eva_Isanta_-_Seminci_2016.jpg',
    characters: ['Bea Villarejo'],
    interprete: 'Eva Isanta',
    tags: ['personaje', 'reparto', 'eva isanta'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:eva-isanta-2',
    type: 'image',
    category: 'character',
    title: 'Eva Isanta en Vila-real. ELVIRA FOLGUERÀ',
    localPath: '/media/licensed/eva-isanta-2.webp',
    miniPath: '/media/licensed/eva-isanta-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:ElviraFolguera0631.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:ElviraFolguera0631.jpg',
    characters: ['Bea Villarejo'],
    interprete: 'Eva Isanta',
    tags: ['personaje', 'reparto', 'eva isanta'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Premios Nacionales Aquí TV · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:roberto-san-martin',
    type: 'image',
    category: 'character',
    title: 'Plaza San Martín y Teatro español en Azul, Provincia de Buenos Aires, Argentina.',
    localPath: '/media/licensed/roberto-san-martin.webp',
    miniPath: '/media/licensed/roberto-san-martin-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Plaza_San_Mart%C3%ADn_y_Teatro_espa%C3%B1ol_en_Azul.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Plaza_San_Mart%C3%ADn_y_Teatro_espa%C3%B1ol_en_Azul.jpg',
    characters: ['Yago'],
    interprete: 'Roberto San Martín',
    tags: ['personaje', 'reparto', 'roberto san martín'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Roberto Fiadone · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:roberto-san-martin-2',
    type: 'image',
    category: 'character',
    title: 'This is a photo of an Argentine monument identified by the ID',
    localPath: '/media/licensed/roberto-san-martin-2.webp',
    miniPath: '/media/licensed/roberto-san-martin-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Palacio_San_Mart%C3%ADn_Puerta_de_hierro.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Palacio_San_Mart%C3%ADn_Puerta_de_hierro.jpg',
    characters: ['Yago'],
    interprete: 'Roberto San Martín',
    tags: ['personaje', 'reparto', 'roberto san martín'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Roberto Fiadone · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:beatriz-carvajal',
    type: 'image',
    category: 'character',
    title: 'Muro de la sacristía. Sepulcros de los Vargas, Ulloa, Carvajal y de Luis de Camargo y esposa.',
    localPath: '/media/licensed/beatriz-carvajal.webp',
    miniPath: '/media/licensed/beatriz-carvajal-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sepulcros_en_la_Iglesia_de_San_Mart%C3%ADn_(Trujillo).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Sepulcros_en_la_Iglesia_de_San_Mart%C3%ADn_(Trujillo).jpg',
    characters: ['María Jesús Vázquez'],
    interprete: 'Beatriz Carvajal',
    tags: ['personaje', 'reparto', 'beatriz carvajal'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: José Luis Filpo Cabana · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:beatriz-carvajal-2',
    type: 'image',
    category: 'character',
    title: 'Unidad deportiva Ángel Carvajal en Apetatitlán, Tlaxcala',
    localPath: '/media/licensed/beatriz-carvajal-2.webp',
    miniPath: '/media/licensed/beatriz-carvajal-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Unidad_deportiva_%C3%81ngel_Carvajal_en_Apetatitl%C3%A1n,_Tlaxcala_01.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Unidad_deportiva_%C3%81ngel_Carvajal_en_Apetatitl%C3%A1n,_Tlaxcala_01.jpg',
    characters: ['María Jesús Vázquez'],
    interprete: 'Beatriz Carvajal',
    tags: ['personaje', 'reparto', 'beatriz carvajal'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Isaacvp · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:nicolas-duenas',
    type: 'image',
    category: 'character',
    title: 'Contaminación hídrica del río Rímac',
    localPath: '/media/licensed/nicolas-duenas.webp',
    miniPath: '/media/licensed/nicolas-duenas-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vista_del_r%C3%ADo_R%C3%ADmac_desde_el_puente_Nicol%C3%A1s_Due%C3%B1as.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Vista_del_r%C3%ADo_R%C3%ADmac_desde_el_puente_Nicol%C3%A1s_Due%C3%B1as.jpg',
    characters: ['Rafael Álvarez'],
    interprete: 'Nicolás Dueñas',
    tags: ['personaje', 'reparto', 'nicolás dueñas'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Angie Valle Jayo · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:nicolas-duenas-2',
    type: 'image',
    category: 'character',
    title: 'Birth Year: 1915 Spouse: [Blank] Admission Year: 1943 Court: District',
    localPath: '/media/licensed/nicolas-duenas-2.webp',
    miniPath: '/media/licensed/nicolas-duenas-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:DUENAS_VICENTE_SAN_NICOLAS_-_DPLA_-_28481617e958865e45f232fea7acb8b1.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:DUENAS_VICENTE_SAN_NICOLAS_-_DPLA_-_28481617e958865e45f232fea7acb8b1.jpg',
    characters: ['Rafael Álvarez'],
    interprete: 'Nicolás Dueñas',
    tags: ['personaje', 'reparto', 'nicolás dueñas'],
    usageStatus: 'licensed',
    license: 'Public domain',
    attribution: 'Foto: U.S. District Court for the District of Massachusetts. 1789 · Public domain · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:vanesa-romero',
    type: 'image',
    category: 'character',
    title: 'Vanesa Romero at Red Carpet of Goya Awards 2026 in Barcelona',
    localPath: '/media/licensed/vanesa-romero.webp',
    miniPath: '/media/licensed/vanesa-romero-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026_-_Vanesa_Romero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026_-_Vanesa_Romero.jpg',
    characters: ['Ana'],
    interprete: 'Vanesa Romero',
    tags: ['personaje', 'reparto', 'vanesa romero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:vanesa-romero-2',
    type: 'image',
    category: 'character',
    title: 'Vanesa Romero en la alfombra roja del Festival de Málaga 2024 frente al Teatro Cervantes',
    localPath: '/media/licensed/vanesa-romero-2.webp',
    miniPath: '/media/licensed/vanesa-romero-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Vanesa_Romero.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Festival_de_M%C3%A1laga_2024_-_Vanesa_Romero.jpg',
    characters: ['Ana'],
    interprete: 'Vanesa Romero',
    tags: ['personaje', 'reparto', 'vanesa romero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:carmen-balague',
    type: 'image',
    category: 'character',
    title: 'Las actrices Imma Colomer, Rosa Gàmiz y Carme Balagué en el estreno de la película Fènix 11:23.',
    localPath: '/media/licensed/carmen-balague.webp',
    miniPath: '/media/licensed/carmen-balague-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Colomer-G%C3%A0miz-Balagu%C3%A9.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Colomer-G%C3%A0miz-Balagu%C3%A9.jpg',
    characters: ['Nieves Cuesta'],
    interprete: 'Carmen Balagué',
    tags: ['personaje', 'reparto', 'carmen balagué'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Moritz Barcelona/Oriol Miralles · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:carmen-balague-2',
    type: 'image',
    category: 'character',
    title: 'Las actrices Imma Colomer, Rosa Gàmiz y Carme Balagué en el estreno de la película Fènix 11:23.',
    localPath: '/media/licensed/carmen-balague-2.webp',
    miniPath: '/media/licensed/carmen-balague-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carmen_Balagu%C3%A9_Colomer-G%C3%A0miz-Balagu%C3%A9_(cropped).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Carmen_Balagu%C3%A9_Colomer-G%C3%A0miz-Balagu%C3%A9_(cropped).jpg',
    characters: ['Nieves Cuesta'],
    interprete: 'Carmen Balagué',
    tags: ['personaje', 'reparto', 'carmen balagué'],
    usageStatus: 'licensed',
    license: 'CC BY 2.0',
    attribution: 'Foto: Moritz Barcelona/Oriol Miralles · CC BY 2.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:cristina-castano',
    type: 'image',
    category: 'character',
    title: 'Premios Goya 2017',
    localPath: '/media/licensed/cristina-castano.webp',
    miniPath: '/media/licensed/cristina-castano-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cristina_Casta%C3%B1o_en_los_Premios_Goya_2017.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Cristina_Casta%C3%B1o_en_los_Premios_Goya_2017.jpg',
    characters: ['Bea'],
    interprete: 'Cristina Castaño',
    tags: ['personaje', 'reparto', 'cristina castaño'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Ruben Ortega · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:cristina-castano-2',
    type: 'image',
    category: 'character',
    title: 'Cristina Castaño en la alfombra roja de los Premios Goya 2024 celebrados en Valladolid',
    localPath: '/media/licensed/cristina-castano-2.webp',
    miniPath: '/media/licensed/cristina-castano-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Cristina_Casta%C3%B1o.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Goyas_2024_-_Cristina_Casta%C3%B1o.jpg',
    characters: ['Bea'],
    interprete: 'Cristina Castaño',
    tags: ['personaje', 'reparto', 'cristina castaño'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:emilio-gutierrez-caba',
    type: 'image',
    category: 'character',
    title: 'Emilio Gutiérrez Caba at Red Carpet of Goya Awards 2026 in Barcelona',
    localPath: '/media/licensed/emilio-gutierrez-caba.webp',
    miniPath: '/media/licensed/emilio-gutierrez-caba-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026-_Emilio_Guti%C3%A9rrez_Caba-3.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026-_Emilio_Guti%C3%A9rrez_Caba-3.jpg',
    characters: ['Padre de Juan'],
    interprete: 'Emilio Gutiérrez Caba',
    tags: ['personaje', 'reparto', 'emilio gutiérrez caba'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:emilio-gutierrez-caba-2',
    type: 'image',
    category: 'character',
    title: 'Emilio Gutiérrez Caba at Red Carpet of Goya Awards 2026 in Barcelona',
    localPath: '/media/licensed/emilio-gutierrez-caba-2.webp',
    miniPath: '/media/licensed/emilio-gutierrez-caba-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026-_Emilio_Guti%C3%A9rrez_Caba.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Premios_Goya_2026-_Emilio_Guti%C3%A9rrez_Caba.jpg',
    characters: ['Padre de Juan'],
    interprete: 'Emilio Gutiérrez Caba',
    tags: ['personaje', 'reparto', 'emilio gutiérrez caba'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Pedro J Pacheco · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:antonio-molero',
    type: 'image',
    category: 'character',
    title: 'Antonio Molero, premio Un León en el Foro en la Peña Athletic Club de Bilbao de Euskal Etxea Madrid, (2017)',
    localPath: '/media/licensed/antonio-molero.webp',
    miniPath: '/media/licensed/antonio-molero-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Antonio_Molero,_premio_Un_Le%C3%B3n_en_el_Foro_(2017).jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Antonio_Molero,_premio_Un_Le%C3%B3n_en_el_Foro_(2017).jpg',
    characters: ['Ramón'],
    interprete: 'Antonio Molero',
    tags: ['personaje', 'reparto', 'antonio molero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Malopez 21 · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
  {
    id: 'commons:antonio-molero-2',
    type: 'image',
    category: 'character',
    title: 'Antonio Molero, 6º premio un León en el Foro la Peña Athletic Club de Bilbao de Euskal Etxea Madrid',
    localPath: '/media/licensed/antonio-molero-2.webp',
    miniPath: '/media/licensed/antonio-molero-2-mini.webp',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Antonio_Molero,_premio_Le%C3%B3n_en_el_Foro.jpg',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Antonio_Molero,_premio_Le%C3%B3n_en_el_Foro.jpg',
    characters: ['Ramón'],
    interprete: 'Antonio Molero',
    tags: ['personaje', 'reparto', 'antonio molero'],
    usageStatus: 'licensed',
    license: 'CC BY-SA 4.0',
    attribution: 'Foto: Malopez 21 · CC BY-SA 4.0 · vía Wikimedia Commons',
    verifiedAt: '2026-08-15',
  },
];
