/**
 * Contenido DEMO de las cuatro familias nuevas de Fase 2:
 * memoria de vecino, ¿qué falta aquí?, la junta y portero automático.
 *
 * Mismo criterio que el resto del banco: comunidad ficticia y original (Travesía del
 * Portalón 13), marcado como contenido demo. Los objetos usan los iconos propios de
 * src/components/portal/icons.tsx.
 */

import { falta, junta, mem, timbres } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

// ── MEMORIA DE VECINO ────────────────────────────────────────────────────────

const MEMORIA: QuestionRecord[] = [
  mem({
    id: 'mem-rellano-lunes',
    prompt: 'El rellano del segundo, un lunes por la mañana. Mira bien.',
    items: ['buzon:Buzón', 'felpudo:Felpudo', 'paraguas:Paraguas', 'periodico:Periódico'],
    question: '¿Qué había apoyado en la pared?',
    options: ['Un paraguas', 'Una escoba', 'Una bicicleta', 'Un cubo'],
    correct: 0,
    difficulty: 3,
    category: 'lugares',
    explanation: 'Un paraguas, todavía mojado del sábado.',
    tags: ['memoria', 'rellano'],
  }),
  mem({
    id: 'mem-garita-amancio',
    prompt: 'La garita de Amancio con la puerta abierta. Cinco segundos.',
    items: ['reloj:Reloj', 'llave:Llave', 'taza:Taza', 'radio:Radio', 'sobre:Sobre'],
    question: '¿Qué NO estaba en la garita?',
    options: ['Una bombilla suelta', 'Un reloj', 'Una taza', 'Una radio'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Bombilla no había: Amancio las guarda en el cuarto de contadores.',
    characters: [N.amancio],
    tags: ['memoria', 'portero'],
  }),
  mem({
    id: 'mem-cuarto-contadores',
    prompt: 'El cuarto de contadores, con la luz que va y viene.',
    items: ['contador:Contador', 'bombilla:Bombilla', 'escoba:Escoba', 'cubo:Cubo'],
    question: '¿Cuántos objetos había en total?',
    options: ['Cuatro', 'Tres', 'Cinco', 'Seis'],
    correct: 0,
    difficulty: 6,
    category: 'lugares',
    explanation: 'Cuatro: contador, bombilla, escoba y cubo.',
    tags: ['memoria', 'contadores'],
    studySeconds: 4,
  }),
  mem({
    id: 'mem-mesa-junta',
    prompt: 'La mesa de la junta antes de empezar.',
    items: ['periodico:Acta', 'taza:Café', 'reloj:Reloj', 'sobre:Circular', 'bolsa:Bolsa'],
    question: '¿Qué había junto al acta?',
    options: ['Un café', 'Una llave', 'Un paraguas', 'Una maceta'],
    correct: 0,
    difficulty: 4,
    category: 'situaciones',
    explanation: 'El café de Charo, que nunca falta en una junta.',
    characters: [N.charo],
    tags: ['memoria', 'junta'],
  }),
  mem({
    id: 'mem-portal-mudanza',
    prompt: 'El portal el día de la mudanza del 1ºB.',
    items: ['caja:Caja', 'bolsa:Bolsa', 'silla:Silla', 'bicicleta:Bicicleta', 'papelera:Papelera'],
    question: '¿Qué estorbaba en medio del portal?',
    options: ['Una silla', 'Un extintor', 'Una maceta', 'Un felpudo'],
    correct: 0,
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Una silla plegable de las de la comunidad, cómo no.',
    characters: [N.kevin],
    tags: ['memoria', 'mudanza'],
  }),
  mem({
    id: 'mem-azotea-antena',
    prompt: 'La azotea después de la tormenta.',
    items: ['maceta:Maceta', 'cubo:Cubo', 'paraguas:Paraguas', 'caja:Caja'],
    question: '¿Qué objeto había volcado?',
    options: ['Un cubo', 'Una silla', 'Una papelera', 'Una radio'],
    correct: 0,
    difficulty: 7,
    category: 'lugares',
    explanation: 'El cubo, que llevaba tres años ahí sin dueño conocido.',
    season: 4,
    tags: ['memoria', 'azotea'],
  }),
  mem({
    id: 'mem-buzones-viernes',
    prompt: 'La pared de buzones un viernes por la tarde.',
    items: ['sobre:Sobre', 'periodico:Periódico', 'buzon:Buzón abierto', 'llave:Llave olvidada'],
    question: '¿Qué se había dejado alguien puesto?',
    options: ['Una llave', 'Un paraguas', 'Una bolsa', 'Un reloj'],
    correct: 0,
    difficulty: 6,
    category: 'lugares',
    explanation: 'Una llave en la cerradura del buzón. Radio Patio tardó diez minutos en saberlo.',
    tags: ['memoria', 'buzones'],
  }),
  mem({
    id: 'mem-bar-faroles',
    prompt: 'La barra del Bar Los Faroles a media mañana.',
    items: ['taza:Café', 'periodico:Periódico', 'radio:Radio', 'reloj:Reloj', 'bolsa:Bolsa'],
    question: '¿Qué estaba encendido?',
    options: ['La radio', 'La tele', 'Una bombilla', 'El extractor'],
    correct: 0,
    difficulty: 5,
    category: 'general',
    explanation: 'La radio de Susi, siempre con las noticias del barrio.',
    characters: [N.susi],
    tags: ['memoria', 'bar'],
  }),
];

// ── ¿QUÉ FALTA AQUÍ? ─────────────────────────────────────────────────────────

const QUE_FALTA: QuestionRecord[] = [
  falta({
    id: 'falta-portal-basico',
    prompt: '¿Qué falta en el portal?',
    sceneLabel: 'El portal de Travesía del Portalón, 13',
    present: ['buzon:Buzones', 'felpudo:Felpudo', 'telefonillo:Telefonillo', 'papelera:Papelera'],
    options: ['extintor:Extintor', 'buzon:Buzones', 'felpudo:Felpudo', 'telefonillo:Telefonillo'],
    correct: 0,
    difficulty: 3,
    category: 'lugares',
    explanation: 'El extintor: se lo llevaron a revisar en la segunda temporada y no volvió.',
    tags: ['visual', 'portal'],
  }),
  falta({
    id: 'falta-garita',
    prompt: 'La garita de la portería… con algo menos de lo normal.',
    sceneLabel: 'Garita de Amancio',
    present: ['reloj:Reloj', 'taza:Taza', 'radio:Radio', 'llave:Llaves'],
    options: ['periodico:Periódico', 'reloj:Reloj', 'radio:Radio', 'llave:Llaves'],
    correct: 0,
    difficulty: 4,
    category: 'personajes',
    explanation: 'Falta el periódico, que Amancio lee de arriba abajo todas las mañanas.',
    characters: [N.amancio],
    tags: ['visual', 'portero'],
  }),
  falta({
    id: 'falta-junta',
    prompt: 'La mesa de la junta, pero hoy falta algo importante.',
    sceneLabel: 'Junta de vecinos',
    present: ['silla:Sillas', 'taza:Café', 'sobre:Circulares', 'reloj:Reloj'],
    options: ['periodico:El acta', 'silla:Sillas', 'taza:Café', 'reloj:Reloj'],
    correct: 0,
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Sin acta no hay junta. O eso dice Charo cada vez.',
    characters: [N.charo],
    tags: ['visual', 'junta'],
  }),
  falta({
    id: 'falta-cuarto-limpieza',
    prompt: 'El cuarto de la limpieza, a medio equipar.',
    sceneLabel: 'Cuarto de la limpieza',
    present: ['cubo:Cubo', 'bolsa:Bolsas', 'papelera:Papelera', 'bombilla:Bombilla'],
    options: ['escoba:Escoba', 'cubo:Cubo', 'papelera:Papelera', 'bolsa:Bolsas'],
    correct: 0,
    difficulty: 3,
    category: 'lugares',
    explanation: 'La escoba. Nadie sabe dónde está la escoba. Nunca.',
    tags: ['visual', 'limpieza'],
  }),
  falta({
    id: 'falta-rellano-nieves',
    prompt: 'El rellano del 1ºA, con la puerta entreabierta.',
    sceneLabel: 'Rellano del primero',
    present: ['felpudo:Felpudo', 'maceta:Maceta', 'paraguas:Paraguas', 'periodico:Periódico'],
    options: ['gato:La gata Pelusa', 'felpudo:Felpudo', 'maceta:Maceta', 'paraguas:Paraguas'],
    correct: 0,
    difficulty: 4,
    category: 'tramas',
    explanation: 'Falta Pelusa. Y así empezó la tercera temporada.',
    characters: [N.nieves],
    season: 3,
    tags: ['visual', 'pelusa'],
  }),
  falta({
    id: 'falta-garaje',
    prompt: 'La plaza 7 del garaje, sospechosamente despejada.',
    sceneLabel: 'Garaje, plaza 7',
    present: ['caja:Cajas', 'cubo:Cubo', 'bolsa:Bolsa', 'papelera:Papelera'],
    options: ['bicicleta:La bicicleta', 'caja:Cajas', 'cubo:Cubo', 'bolsa:Bolsa'],
    correct: 0,
    difficulty: 6,
    category: 'lugares',
    explanation: 'Sin bicicletas de Braulio la plaza 7 parece otra.',
    characters: [N.braulio],
    season: 5,
    tags: ['visual', 'garaje'],
  }),
  falta({
    id: 'falta-bar',
    prompt: 'La barra del bar, con un hueco raro.',
    sceneLabel: 'Bar Los Faroles',
    present: ['taza:Cafés', 'periodico:Periódico', 'reloj:Reloj', 'bolsa:Bolsa'],
    options: ['radio:La radio', 'taza:Cafés', 'reloj:Reloj', 'periodico:Periódico'],
    correct: 0,
    difficulty: 5,
    category: 'general',
    explanation: 'Sin la radio de Susi el bar no es el bar.',
    characters: [N.susi],
    tags: ['visual', 'bar'],
  }),
  falta({
    id: 'falta-contadores',
    prompt: 'El cuarto de contadores a oscuras. ¿Qué no está?',
    sceneLabel: 'Cuarto de contadores',
    present: ['contador:Contadores', 'llave:Llave', 'caja:Caja', 'escoba:Escoba'],
    options: ['bombilla:Bombilla', 'contador:Contadores', 'llave:Llave', 'caja:Caja'],
    correct: 0,
    difficulty: 4,
    category: 'lugares',
    explanation: 'Falta la bombilla: por eso está a oscuras.',
    tags: ['visual', 'contadores'],
  }),
];

// ── LA JUNTA (decisiones) ────────────────────────────────────────────────────

const LA_JUNTA: QuestionRecord[] = [
  junta({
    id: 'junta-ascensor-parado',
    prompt: 'Presides la junta y hay que decidir ya.',
    situation:
      'El ascensor se ha parado dos veces esta semana con vecinos dentro. Yeyo dice que lo arregla él por 80 €; la empresa oficial pide 2.400 € y tarda un mes.',
    decisiones: [
      {
        texto: 'Contratar a la empresa oficial y aprobar la derrama',
        peso: 1,
        consecuencia: 'Cuesta dinero y paciencia, pero el ascensor deja de encerrar gente.',
      },
      {
        texto: 'Que lo mire Yeyo mientras se pide presupuesto',
        peso: 0.6,
        consecuencia: 'Solución temporal razonable… si de verdad se pide el presupuesto.',
      },
      {
        texto: 'Dejarlo estar, total funciona casi siempre',
        peso: 0.1,
        consecuencia: 'A la semana siguiente se queda dentro Doña Fefa. Junta extraordinaria.',
      },
      {
        texto: 'Prohibir usar el ascensor a los del primero',
        peso: 0,
        consecuencia: 'Nadie entiende la medida y el acta se llena de reclamaciones.',
      },
    ],
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Lo caro suele ser lo barato cuando hay gente dentro del ascensor.',
    characters: [N.yeyo, N.charo],
    season: 1,
    tags: ['junta', 'ascensor'],
  }),
  junta({
    id: 'junta-gotera',
    prompt: 'La gotera del primero llega a la junta.',
    situation:
      'Nieves tiene una mancha creciente en el techo. Ramiro asegura que su obra no tiene nada que ver. La administradora no coge el teléfono.',
    decisiones: [
      {
        texto: 'Encargar un informe técnico y repartir el coste según resultado',
        peso: 1,
        consecuencia: 'Se sabe de dónde viene el agua y paga quien debe. Aburrido y justo.',
      },
      {
        texto: 'Que Ramiro pare la obra hasta aclararlo',
        peso: 0.5,
        consecuencia: 'Frena el problema, pero sin informe la discusión vuelve en dos semanas.',
      },
      {
        texto: 'Pagarlo del fondo de reserva y no molestar a nadie',
        peso: 0.3,
        consecuencia: 'La mancha se pinta, el agua sigue. El fondo, más pobre.',
      },
      {
        texto: 'Esperar a ver si se seca solo',
        peso: 0,
        consecuencia: 'Se seca en agosto y vuelve en octubre, con amigos.',
      },
    ],
    difficulty: 6,
    category: 'tramas',
    explanation: 'Primero el diagnóstico, después la factura.',
    characters: [N.nieves, N.ramiro, N.loli],
    season: 2,
    tags: ['junta', 'gotera'],
  }),
  junta({
    id: 'junta-moto-portal',
    prompt: 'La moto de Kevin, otra vez en el portal.',
    situation:
      'Kevin aparca la moto junto a los buzones porque en la calle se la han rayado dos veces. Braulio ha traído una circular firmada por él mismo.',
    decisiones: [
      {
        texto: 'Habilitar un hueco en el garaje para motos',
        peso: 1,
        consecuencia: 'Cuesta organizarlo, pero resuelve el problema de verdad.',
      },
      {
        texto: 'Permitirlo solo por la noche',
        peso: 0.6,
        consecuencia: 'Acuerdo tibio que casi todos cumplen. Casi.',
      },
      {
        texto: 'Prohibirlo y multar a quien lo haga',
        peso: 0.3,
        consecuencia: 'La comunidad no puede multar. La moto sigue ahí y ahora hay enfado.',
      },
      {
        texto: 'Sacar la moto a la calle entre varios vecinos',
        peso: 0,
        consecuencia: 'Eso es tocar lo ajeno. Termina en denuncia y en Radio Patio.',
      },
    ],
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Cuando algo se repite, el problema es el sitio, no la persona.',
    characters: [N.kevin, N.braulio],
    season: 5,
    tags: ['junta', 'garaje'],
  }),
  junta({
    id: 'junta-wifi',
    prompt: 'El WiFi comunitario no llega arriba.',
    situation:
      'Las plantas altas se quedan sin señal. Vichi propone un repetidor en la escalera; alguien lo desenchufa cada semana para aspirar.',
    decisiones: [
      {
        texto: 'Instalar un enchufe dedicado para el repetidor',
        peso: 1,
        consecuencia: 'Cuarenta euros y se acaba la guerra del enchufe.',
      },
      {
        texto: 'Poner un cartel pidiendo que no lo desenchufen',
        peso: 0.4,
        consecuencia: 'El cartel dura tres días. El enchufe sigue siendo uno.',
      },
      {
        texto: 'Cambiar de compañía a ver si mejora',
        peso: 0.2,
        consecuencia: 'Mismo problema, contrato nuevo y dos semanas sin internet.',
      },
      {
        texto: 'Que cada uno se pague su línea',
        peso: 0.1,
        consecuencia: 'Se acabó el WiFi comunitario y con él parte del vecindario.',
      },
    ],
    difficulty: 6,
    category: 'tramas',
    explanation: 'El problema no era la antena: era que había un solo enchufe.',
    characters: [N.vichi],
    season: 4,
    tags: ['junta', 'wifi'],
  }),
  junta({
    id: 'junta-derrama-impago',
    prompt: 'Hay un vecino que no paga la derrama.',
    situation:
      'Un propietario lleva tres meses sin pagar su parte de la derrama del ascensor. Dice que él no lo usa.',
    decisiones: [
      {
        texto: 'Enviar un requerimiento por escrito con plazo',
        peso: 1,
        consecuencia: 'Es el paso correcto: queda constancia y suele bastar.',
      },
      {
        texto: 'Hablar con él en el rellano de buen rollo',
        peso: 0.6,
        consecuencia: 'A veces funciona y ahorra un mal rato. A veces solo retrasa el requerimiento.',
      },
      {
        texto: 'Comentarlo en el grupo del portal para presionar',
        peso: 0.1,
        consecuencia: 'Radio Patio se pone en marcha y el asunto se convierte en enemistad.',
      },
      {
        texto: 'Cortarle el agua',
        peso: 0,
        consecuencia: 'Ilegal, injusto y carísimo cuando llegue la demanda.',
      },
    ],
    difficulty: 7,
    category: 'situaciones',
    explanation: 'Aburrido pero eficaz: por escrito y con plazo.',
    characters: [N.braulio, N.loli],
    tags: ['junta', 'derrama'],
  }),
  junta({
    id: 'junta-ruido-vichi',
    prompt: 'El bajo de las tres de la madrugada.',
    situation:
      'Vichi ensaya de noche porque trabaja de día. Doña Fefa duerme justo debajo y ya ha bajado dos veces en bata.',
    decisiones: [
      {
        texto: 'Acordar un horario y ayudarle a insonorizar el cuarto',
        peso: 1,
        consecuencia: 'Cuesta un fin de semana de trabajo y todos duermen.',
      },
      {
        texto: 'Fijar un horario de silencio y ya está',
        peso: 0.7,
        consecuencia: 'Correcto y sencillo, aunque Vichi tendrá que buscarse la vida.',
      },
      {
        texto: 'Que Doña Fefa se cambie de habitación',
        peso: 0.1,
        consecuencia: 'La afectada no es la que tiene que mudarse. Malestar general.',
      },
      {
        texto: 'Denunciar directamente sin avisar',
        peso: 0.2,
        consecuencia: 'Legal, pero rompe la convivencia sin haber intentado hablar.',
      },
    ],
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Primero hablar, después normas, y la denuncia como último recurso.',
    characters: [N.vichi, N.fefa],
    tags: ['junta', 'ruido'],
  }),
];

// ── PORTERO AUTOMÁTICO (secuencias) ──────────────────────────────────────────

const PORTERO: QuestionRecord[] = [
  timbres({
    id: 'seq-buenos-dias',
    prompt: 'Alguien llama a varios timbres seguidos. Repite el orden.',
    pads: ['1ºA', '2ºB', '3ºA', '4ºB'],
    secuencia: [0, 2, 1],
    difficulty: 3,
    category: 'general',
    explanation: 'Primero al primero, luego al tercero y por último al segundo.',
    tags: ['secuencia', 'telefonillo'],
  }),
  timbres({
    id: 'seq-reparto',
    prompt: 'El repartidor prueba portero por portero. ¿En qué orden?',
    pads: ['Bajo C', '1ºB', '2ºA', '3ºB'],
    secuencia: [1, 3, 0, 2],
    difficulty: 5,
    category: 'personajes',
    explanation: 'Kevin siempre empieza por su propio timbre por si acaso.',
    characters: [N.kevin],
    tags: ['secuencia', 'reparto'],
  }),
  timbres({
    id: 'seq-junta-convocatoria',
    prompt: 'Charo avisa de la junta timbre a timbre.',
    pads: ['1ºA', '2ºB', '3ºB', '4ºA', 'Portería'],
    secuencia: [4, 0, 2, 1],
    difficulty: 6,
    category: 'situaciones',
    explanation: 'Primero a la portería, que es de donde salen las llaves.',
    characters: [N.charo],
    tags: ['secuencia', 'junta'],
  }),
  timbres({
    id: 'seq-radio-patio',
    prompt: 'Las hermanas Bocanegra difunden la noticia.',
    pads: ['1ºA', '1ºB', '3ºA', '4ºB'],
    secuencia: [2, 0, 3, 1],
    difficulty: 7,
    category: 'personajes',
    explanation: 'Empiezan por el 3ºA, que es el que más habla.',
    characters: [N.puri, N.sagrario],
    tags: ['secuencia', 'radio-patio'],
    stepMs: 550,
  }),
  timbres({
    id: 'seq-averia',
    prompt: 'El técnico prueba los timbres para localizar la avería.',
    pads: ['Bajo A', 'Bajo C', '2ºA', '4ºA', 'Ático'],
    secuencia: [0, 1, 4, 3, 2],
    difficulty: 9,
    category: 'lugares',
    explanation: 'De abajo arriba, saltando al ático porque es donde falla.',
    tags: ['secuencia', 'averia'],
    stepMs: 520,
  }),
  timbres({
    id: 'seq-visita',
    prompt: 'Una visita despistada prueba tres timbres.',
    pads: ['1ºA', '2ºB', '3ºA', '4ºB'],
    secuencia: [3, 3, 1],
    difficulty: 8,
    category: 'general',
    explanation: 'Insistió dos veces en el 4ºB antes de bajar al 2ºB.',
    tags: ['secuencia', 'visita'],
  }),
];

export const FASE2_QUESTIONS: QuestionRecord[] = [
  ...MEMORIA,
  ...QUE_FALTA,
  ...LA_JUNTA,
  ...PORTERO,
];
