/** Categoría GENERAL — cultura general del portal. Contenido DEMO. */

import { bet, imp, mc, ord, tf } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

export const GENERAL_QUESTIONS: QuestionRecord[] = [
  mc({
    id: 'gen-direccion',
    prompt: '¿En qué dirección está el portal donde pasa todo?',
    options: ['Travesía del Portalón, 13', 'Calle del Desagüe, 3', 'Plaza de la Derrama, 8', 'Cuesta del Felpudo, 21'],
    correct: 0,
    difficulty: 1,
    category: 'general',
    explanation: 'Travesía del Portalón, 13. Cinco plantas, bajo comercial y un ático con más macetas que vecinos.',
    tags: ['portal', 'básico'],
  }),
  mc({
    id: 'gen-anio-construccion',
    prompt: '¿En qué año se construyó el edificio?',
    options: ['1968', '1952', '1979', '1984'],
    correct: 0,
    difficulty: 4,
    category: 'general',
    explanation: '1968, y se nota en las tuberías.',
    tags: ['edificio'],
  }),
  mc({
    id: 'gen-cargo-charo',
    prompt: '¿Qué cargo ocupa Charo Peláez en la comunidad?',
    options: ['Presidenta', 'Administradora', 'Secretaria', 'Portera'],
    correct: 0,
    difficulty: 2,
    category: 'general',
    explanation: 'Presidenta desde 2019, con carpeta de tapas rojas incluida.',
    characters: [N.charo],
    tags: ['junta'],
  }),
  mc({
    id: 'gen-quien-administra',
    prompt: '¿Qué empresa lleva la administración de la finca?',
    options: ['Fincas Tabares', 'Gestora Portalón', 'Inmuebles Quiles', 'Patio & Asociados'],
    correct: 0,
    difficulty: 5,
    category: 'general',
    explanation: 'Fincas Tabares, de Loli Tabares. Los viernes no coge el teléfono.',
    characters: [N.loli],
    tags: ['administración'],
  }),
  mc({
    id: 'gen-bar-bajo',
    prompt: '¿Cómo se llama el bar del bajo comercial?',
    options: ['Bar Los Faroles', 'Bar La Derrama', 'Cafetería El Rellano', 'Bar Pelusa'],
    correct: 0,
    difficulty: 3,
    category: 'general',
    explanation: 'Bar Los Faroles, cuartel general oficioso de la comunidad.',
    characters: [N.susi],
    tags: ['bar', 'lugares'],
  }),
  mc({
    id: 'gen-marca-ascensor',
    prompt: '¿De qué año es el ascensor del portal?',
    options: ['1974', '1968', '1991', '2004'],
    correct: 0,
    difficulty: 7,
    category: 'general',
    explanation: 'Un Otis de 1974. Se para entre el segundo y el tercero por costumbre.',
    tags: ['ascensor'],
  }),
  mc({
    id: 'gen-wifi',
    prompt: '¿Cómo se llama la red WiFi comunitaria?',
    options: ['PORTALON13_FIBRA', 'RADIOPATIO_5G', 'JUNTA_LIBRE', 'FINCAS_TABARES'],
    correct: 0,
    difficulty: 6,
    category: 'general',
    explanation: 'PORTALON13_FIBRA, con la contraseña apuntada en el tablón. Dos veces.',
    tags: ['wifi', 'temporada-4'],
    season: 4,
  }),
  mc({
    id: 'gen-anios-portero',
    prompt: '¿Cuántos años lleva Amancio Quintela en la portería?',
    options: ['31', '12', '20', '45'],
    correct: 0,
    difficulty: 6,
    category: 'general',
    explanation: 'Treinta y un años. Y lo recuerda en cada junta.',
    characters: [N.amancio],
    tags: ['portero'],
  }),
  mc({
    id: 'gen-importe-derrama',
    prompt: '¿De cuánto fue la derrama del ascensor de la primera temporada?',
    options: ['2.400 €', '900 €', '5.000 €', '340 €'],
    correct: 0,
    difficulty: 7,
    category: 'general',
    explanation: '2.400 €. Braulio pidió que constara en acta su desacuerdo. Tres veces.',
    characters: [N.braulio],
    season: 1,
    tags: ['derrama'],
  }),
  mc({
    id: 'gen-mes-junta',
    prompt: '¿En qué mes se celebra la junta ordinaria que siempre dura cuatro horas?',
    options: ['Julio', 'Enero', 'Octubre', 'Marzo'],
    correct: 0,
    difficulty: 5,
    category: 'general',
    explanation: 'Julio, con 34 grados y sin aire acondicionado en el portal.',
    tags: ['junta'],
  }),
  mc({
    id: 'gen-instrumento-vichi',
    prompt: '¿Qué instrumento ensaya Vichi Nadal a las tres de la madrugada?',
    options: ['El bajo', 'La batería', 'El acordeón', 'El violín'],
    correct: 0,
    difficulty: 4,
    category: 'general',
    explanation: 'El bajo. Se oye mejor en el 3ºB que en su propio salón.',
    characters: [N.vichi],
    tags: ['ruido'],
  }),
  mc({
    id: 'gen-gata',
    prompt: '¿Cómo se llama la gata de Nieves Arrondo?',
    options: ['Pelusa', 'Bigotes', 'Derrama', 'Nube'],
    correct: 0,
    difficulty: 3,
    category: 'general',
    explanation: 'Pelusa. Desapareció siete días y estaba en el trastero 4.',
    characters: [N.nieves],
    season: 3,
    tags: ['pelusa'],
  }),
  tf({
    id: 'gen-tf-portero-felpudo',
    prompt: 'Amancio Quintela permite que cualquiera mueva su felpudo de la garita.',
    answer: false,
    difficulty: 2,
    category: 'general',
    explanation: 'El felpudo de Amancio es intocable. Es prácticamente patrimonio del portal.',
    characters: [N.amancio],
    tags: ['portero'],
  }),
  tf({
    id: 'gen-tf-braulio-vota',
    prompt: 'Braulio Quiles ha votado a favor de todas las derramas de la comunidad.',
    answer: false,
    difficulty: 2,
    category: 'general',
    explanation: 'Braulio vota no. A todo. Incluso a lo que propone él.',
    characters: [N.braulio],
    tags: ['junta', 'derrama'],
  }),
  tf({
    id: 'gen-tf-fefa-1971',
    prompt: 'Doña Fefa Marín vive en el edificio desde 1971.',
    answer: true,
    difficulty: 5,
    category: 'general',
    explanation: 'Desde 1971. Ha visto pasar tres administradores y cuatro presidentes.',
    characters: [N.fefa],
    tags: ['veteranos'],
  }),
  tf({
    id: 'gen-tf-atico-vacio',
    prompt: 'Los Tremiño, los del ático, aparecen en casi todas las juntas.',
    answer: false,
    difficulty: 4,
    category: 'general',
    explanation: 'No aparecen nunca. Sus macetas tienen más presencia que ellos.',
    characters: [N.tremino],
    tags: ['ático'],
  }),
  tf({
    id: 'gen-tf-loli-viernes',
    prompt: 'La administradora Loli Tabares atiende el teléfono los viernes sin problema.',
    answer: false,
    difficulty: 5,
    category: 'general',
    explanation: 'Los viernes, Fincas Tabares entra en modo contestador automático.',
    characters: [N.loli],
    tags: ['administración'],
  }),
  tf({
    id: 'gen-tf-kevin-moto',
    prompt: 'Kevin Salgado deja la moto aparcada en el portal.',
    answer: true,
    difficulty: 3,
    category: 'general',
    explanation: 'En el portal, junto a los buzones. Y sí, ya se ha hablado en la junta.',
    characters: [N.kevin],
    tags: ['portal'],
  }),
  tf({
    id: 'gen-tf-obras-2a',
    prompt: 'Las obras del 2ºA llevan más de un año.',
    answer: true,
    difficulty: 3,
    category: 'general',
    explanation: 'Catorce meses. Ramiro dice que "ya casi está".',
    characters: [N.ramiro, N.chusa],
    season: 2,
    tags: ['obras'],
  }),
  tf({
    id: 'gen-tf-hermanas-silla',
    prompt: 'Las hermanas Bocanegra tienen una silla puesta junto a la ventana del patio.',
    answer: true,
    difficulty: 4,
    category: 'general',
    explanation: 'Turno de mañana Puri, turno de tarde Sagrario. Radio Patio no descansa.',
    characters: [N.puri, N.sagrario],
    tags: ['radio-patio'],
  }),
  tf({
    id: 'gen-tf-yeyo-titulo',
    prompt: 'Yeyo, el sobrino del portero, es técnico titulado en ascensores.',
    answer: false,
    difficulty: 6,
    category: 'general',
    explanation: 'Yeyo arregla el ascensor con una llave Allen y mucha confianza. Titulación, ninguna.',
    characters: [N.yeyo],
    tags: ['ascensor'],
  }),
  tf({
    id: 'gen-tf-plantas',
    prompt: 'El edificio tiene cinco plantas, además del bajo comercial y el ático.',
    answer: true,
    difficulty: 3,
    category: 'general',
    explanation: 'Cinco plantas, bajo y ático. Y un patio de luces que amplifica todo.',
    tags: ['edificio'],
  }),
  imp({
    id: 'gen-imp-vecinos',
    prompt: 'Tres de estos viven en el portal. ¿Quién es el infiltrado?',
    setLabel: 'Vecinos de Travesía del Portalón, 13',
    items: ['Braulio Quiles', 'Nieves Arrondo', 'Vichi Nadal', 'Marcial Ortuño'],
    impostor: 3,
    difficulty: 4,
    category: 'general',
    explanation: 'Marcial Ortuño no vive aquí. Nadie sabe quién es y aun así le llegan cartas.',
    tags: ['vecinos'],
  }),
  imp({
    id: 'gen-imp-cargos',
    prompt: 'Tres son cargos o oficios reales del portal. ¿Cuál está infiltrado?',
    setLabel: 'Oficios y cargos del portal',
    items: ['Presidenta de la comunidad', 'Portero', 'Administradora de fincas', 'Conserje de noche'],
    impostor: 3,
    difficulty: 5,
    category: 'general',
    explanation: 'No hay conserje de noche. Hay Amancio, y a las diez cierra la garita.',
    tags: ['junta'],
  }),
  imp({
    id: 'gen-imp-gastos',
    prompt: 'Tres aparecen en las cuentas de la comunidad. ¿Cuál se ha colado?',
    setLabel: 'Gastos aprobados en junta',
    items: ['Reparación del ascensor', 'Antena de la azotea', 'Limpieza del patio de luces', 'Gimnasio comunitario'],
    impostor: 3,
    difficulty: 4,
    category: 'general',
    explanation: 'El gimnasio se propuso, se rió y se archivó en la misma junta.',
    tags: ['cuentas'],
  }),
  ord({
    id: 'gen-ord-junta',
    prompt: 'Ordena cómo transcurre una junta normal en el portal.',
    steps: [
      'Charo reparte fotocopias del orden del día',
      'Braulio pide que conste en acta su desacuerdo',
      'Alguien saca el tema del ascensor sin venir a cuento',
      'Se aprueba todo tal cual estaba propuesto',
    ],
    difficulty: 5,
    category: 'general',
    explanation: 'Cuatro pasos, cuatro horas. Es matemático.',
    characters: [N.charo, N.braulio],
    tags: ['junta'],
  }),
  ord({
    id: 'gen-ord-paquete',
    prompt: 'Ordena el viaje de un paquete que nadie recoge.',
    steps: [
      'Kevin lo deja en la garita porque no hay nadie',
      'Amancio lo apunta en su libreta',
      'Alguien lo mueve al cuarto de contadores',
      'Aparece tres semanas después en el trastero 4',
    ],
    difficulty: 6,
    category: 'general',
    explanation: 'El trastero 4 es donde van a morir los paquetes y las sillas viejas.',
    characters: [N.kevin, N.amancio],
    tags: ['paquetes'],
  }),
  bet({
    id: 'gen-bet-derrama',
    prompt: 'Última pregunta del día: ¿por cuántos votos se aprobó la derrama del ascensor?',
    options: ['Por un voto', 'Por unanimidad', 'Por cinco votos', 'No se aprobó'],
    correct: 0,
    difficulty: 8,
    category: 'general',
    explanation: 'Por un voto: el de Doña Fefa, delegado por escrito y con la letra temblorosa.',
    characters: [N.fefa, N.braulio],
    season: 1,
    tags: ['derrama', 'final'],
  }),
  bet({
    id: 'gen-bet-trastero',
    prompt: '¿En qué trastero acaban siempre las cosas perdidas del portal?',
    options: ['El trastero 4', 'El trastero 1', 'El cuarto de contadores', 'La azotea'],
    correct: 0,
    difficulty: 7,
    category: 'general',
    explanation: 'Trastero 4: sillas de la comunidad, paquetes huérfanos y una gata durante siete días.',
    tags: ['final', 'trastero'],
  }),
  bet({
    id: 'gen-bet-presidenta',
    prompt: '¿Desde qué año es Charo Peláez presidenta de la comunidad?',
    options: ['2019', '2015', '2021', '2009'],
    correct: 0,
    difficulty: 8,
    category: 'general',
    explanation: 'Desde 2019, cuando nadie más levantó la mano en la junta de julio.',
    characters: [N.charo],
    tags: ['final', 'junta'],
  }),
];
