/** Categoría LUGARES — portal, azotea, contadores y otros escenarios. Contenido DEMO. */

import { bet, imp, mc, tf } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

export const LUGARES_QUESTIONS: QuestionRecord[] = [
  mc({
    id: 'lug-mc-ascensor-para',
    prompt: '¿Entre qué plantas se queda parado el ascensor?',
    options: ['Entre el segundo y el tercero', 'Entre el bajo y el primero', 'Entre el cuarto y el ático', 'En el garaje'],
    correct: 0,
    difficulty: 3,
    category: 'lugares',
    explanation: 'Siempre entre el segundo y el tercero. Es su sitio favorito.',
    tags: ['ascensor'],
  }),
  mc({
    id: 'lug-mc-conciliabulos',
    prompt: '¿Dónde se organizan las conversaciones que no deben oírse en el rellano?',
    options: ['En el cuarto de contadores', 'En la azotea', 'En el garaje', 'En la garita'],
    correct: 0,
    difficulty: 5,
    category: 'lugares',
    explanation: 'El cuarto de contadores: sin ventanas, sin testigos y con eco.',
    tags: ['contadores'],
  }),
  mc({
    id: 'lug-mc-antena',
    prompt: '¿Dónde está la antena comunitaria?',
    options: ['En la azotea', 'En el patio de luces', 'En el ático de los Tremiño', 'En la garita del portero'],
    correct: 0,
    difficulty: 3,
    category: 'lugares',
    explanation: 'En la azotea, sujeta con dos bridas y mucha fe.',
    season: 4,
    tags: ['antena', 'azotea'],
  }),
  mc({
    id: 'lug-mc-plaza-litigio',
    prompt: '¿Qué plaza del garaje está en litigio permanente?',
    options: ['La 7', 'La 1', 'La 12', 'La del portero'],
    correct: 0,
    difficulty: 6,
    category: 'lugares',
    explanation: 'La plaza 7: la moto de Kevin, la raya de Braulio y una junta extraordinaria.',
    characters: [N.kevin, N.braulio],
    season: 5,
    tags: ['garaje'],
  }),
  mc({
    id: 'lug-mc-trastero',
    prompt: '¿Qué guarda el trastero 4?',
    options: [
      'Las sillas de la comunidad y todo lo que se pierde',
      'Los contadores del agua',
      'Las bicicletas de Braulio',
      'El archivo de actas',
    ],
    correct: 0,
    difficulty: 5,
    category: 'lugares',
    explanation: 'Sillas plegables, paquetes olvidados y, una vez, una gata.',
    season: 3,
    tags: ['trastero'],
  }),
  mc({
    id: 'lug-mc-buzones',
    prompt: '¿Qué le pasa al buzón del 3ºB?',
    options: ['No tiene nombre puesto', 'Está soldado', 'Lo comparten dos vecinos', 'No existe'],
    correct: 0,
    difficulty: 7,
    category: 'lugares',
    explanation: 'Sin nombre desde los noventa. Doña Fefa dice que ya sabe cuál es el suyo.',
    characters: [N.fefa],
    tags: ['buzones'],
  }),
  mc({
    id: 'lug-mc-garita',
    prompt: '¿Qué hay colgado en la garita de Amancio?',
    options: ['Un calendario de 1998', 'Un plano del edificio', 'Un retrato de la presidenta', 'Un extintor caducado'],
    correct: 0,
    difficulty: 6,
    category: 'lugares',
    explanation: 'Un calendario de 1998 que, según él, "está bien de días".',
    characters: [N.amancio],
    tags: ['portero'],
  }),
  mc({
    id: 'lug-mc-patio-luces',
    prompt: '¿Para qué sirve realmente el patio de luces?',
    options: [
      'Para que se oiga todo en todas las casas',
      'Para tender la ropa oficialmente',
      'Para guardar bicicletas',
      'Para las reuniones de verano',
    ],
    correct: 0,
    difficulty: 4,
    category: 'lugares',
    explanation: 'Es el altavoz del edificio. Y la ventana favorita de las hermanas Bocanegra.',
    characters: [N.puri, N.sagrario],
    tags: ['patio'],
  }),
  mc({
    id: 'lug-mc-tablon',
    prompt: '¿Dónde aparecen las circulares de la administradora?',
    options: ['En el tablón del portal', 'En los buzones', 'En el ascensor', 'Debajo de cada puerta'],
    correct: 0,
    difficulty: 3,
    category: 'lugares',
    explanation: 'En el tablón, con cuatro chinchetas y una esquina siempre doblada.',
    characters: [N.loli],
    tags: ['tablón'],
  }),
  mc({
    id: 'lug-mc-bar-funcion',
    prompt: '¿Qué función extra cumple el Bar Los Faroles para la comunidad?',
    options: [
      'Guardar paquetes cuando no hay nadie en portería',
      'Celebrar las juntas oficiales',
      'Almacenar las actas',
      'Alquilar sillas',
    ],
    correct: 0,
    difficulty: 5,
    category: 'lugares',
    explanation: 'Susi guarda paquetes, llaves y secretos. Sobre todo secretos.',
    characters: [N.susi],
    tags: ['bar'],
  }),
  tf({
    id: 'lug-tf-azotea-cerrada',
    prompt: 'La azotea está cerrada con llave y solo el portero tiene copia.',
    answer: false,
    difficulty: 6,
    category: 'lugares',
    explanation: 'Hay tres copias circulando: Amancio, Yeyo y una que nadie reconoce tener.',
    characters: [N.amancio, N.yeyo],
    tags: ['azotea'],
  }),
  tf({
    id: 'lug-tf-telefonillo',
    prompt: 'El telefonillo del 2ºB no funciona.',
    answer: true,
    difficulty: 5,
    category: 'lugares',
    explanation: 'No hace falta: las hermanas ya te han visto llegar desde la ventana.',
    characters: [N.puri, N.sagrario],
    tags: ['telefonillo'],
  }),
  tf({
    id: 'lug-tf-escalera-servicio',
    prompt: 'El edificio tiene escalera de servicio.',
    answer: true,
    difficulty: 6,
    category: 'lugares',
    explanation: 'Estrecha, oscura y utilísima para evitar conversaciones.',
    tags: ['escalera'],
  }),
  tf({
    id: 'lug-tf-garaje-plazas',
    prompt: 'El garaje del edificio tiene plazas numeradas.',
    answer: true,
    difficulty: 3,
    category: 'lugares',
    explanation: 'Numeradas y con la 7 en disputa desde la quinta temporada.',
    season: 5,
    tags: ['garaje'],
  }),
  tf({
    id: 'lug-tf-piscina',
    prompt: 'La comunidad tiene piscina comunitaria en la azotea.',
    answer: false,
    difficulty: 2,
    category: 'lugares',
    explanation: 'Hay una antena, dos bridas y macetas ajenas. Piscina, ninguna.',
    tags: ['azotea'],
  }),
  tf({
    id: 'lug-tf-contadores-llave',
    prompt: 'El cuarto de contadores se abre con la misma llave que el portal.',
    answer: false,
    difficulty: 7,
    category: 'lugares',
    explanation: 'Llave propia, y la tiene el portero. Y Yeyo. Y probablemente Braulio.',
    characters: [N.amancio],
    tags: ['contadores'],
  }),
  tf({
    id: 'lug-tf-bar-mismo-edificio',
    prompt: 'El Bar Los Faroles está en el mismo edificio del portal.',
    answer: true,
    difficulty: 2,
    category: 'lugares',
    explanation: 'En el bajo comercial. Cero excusas para no bajar.',
    characters: [N.susi],
    tags: ['bar'],
  }),
  tf({
    id: 'lug-tf-ascensor-atico',
    prompt: 'El ascensor llega hasta el ático.',
    answer: false,
    difficulty: 8,
    category: 'lugares',
    explanation: 'Se queda en el cuarto. Al ático se sube andando, que para eso no vive nadie.',
    characters: [N.tremino],
    tags: ['ascensor', 'ático'],
  }),
  imp({
    id: 'lug-imp-comunes',
    prompt: 'Tres son zonas comunes del edificio. ¿Cuál se ha infiltrado?',
    setLabel: 'Zonas comunes de la finca',
    items: ['El patio de luces', 'La azotea', 'El cuarto de contadores', 'El salón de Nieves'],
    impostor: 3,
    difficulty: 3,
    category: 'lugares',
    explanation: 'El salón del 1ºA es de Nieves, aunque den clases allí.',
    characters: [N.nieves],
  }),
  imp({
    id: 'lug-imp-planta-baja',
    prompt: 'Tres están en la planta baja. ¿Cuál no?',
    setLabel: 'Cosas de la planta baja',
    items: ['Los buzones', 'La garita', 'El Bar Los Faroles', 'La antena comunitaria'],
    impostor: 3,
    difficulty: 4,
    category: 'lugares',
    explanation: 'La antena está en la azotea, cinco plantas más arriba.',
  }),
  imp({
    id: 'lug-imp-ruidos',
    prompt: 'Tres ruidos llegan por el patio de luces. ¿Cuál no viene de ahí?',
    setLabel: 'Ruidos del patio de luces',
    items: ['El bajo de Vichi', 'La radio de Doña Fefa', 'La obra del 2ºA', 'La moto de Kevin'],
    impostor: 3,
    difficulty: 7,
    category: 'lugares',
    explanation: 'La moto se oye en el portal, no en el patio. Es un clásico distinto.',
    characters: [N.kevin, N.vichi],
  }),
  imp({
    id: 'lug-imp-llaves',
    prompt: 'Tres puertas necesitan llave propia. ¿Cuál se abre sin ella?',
    setLabel: 'Puertas con llave propia',
    items: ['Cuarto de contadores', 'Azotea', 'Trastero 4', 'Portal (de día)'],
    impostor: 3,
    difficulty: 6,
    category: 'lugares',
    explanation: 'El portal se queda abierto de día, para desesperación de Amancio.',
    characters: [N.amancio],
  }),
  bet({
    id: 'lug-bet-plaza',
    prompt: 'Y para acabar: ¿qué plaza de garaje provocó una junta extraordinaria?',
    options: ['La 7', 'La 3', 'La 9', 'La 11'],
    correct: 0,
    difficulty: 8,
    category: 'lugares',
    explanation: 'La 7. Y la raya que pintó Braulio sigue ahí, para memoria histórica.',
    characters: [N.braulio, N.kevin],
    season: 5,
    tags: ['final', 'garaje'],
  }),
  bet({
    id: 'lug-bet-calendario',
    prompt: '¿De qué año es el calendario de la garita del portero?',
    options: ['1998', '1988', '2001', '1974'],
    correct: 0,
    difficulty: 9,
    category: 'lugares',
    explanation: '1998. Amancio sostiene que los días caen igual.',
    characters: [N.amancio],
    tags: ['final', 'portero'],
  }),
  bet({
    id: 'lug-bet-trastero-numero',
    prompt: '¿Qué número tiene el trastero donde acaba todo lo perdido?',
    options: ['El 4', 'El 2', 'El 7', 'El 11'],
    correct: 0,
    difficulty: 7,
    category: 'lugares',
    explanation: 'El 4. Sillas, paquetes y una gata con siete días de aventura.',
    season: 3,
    tags: ['final', 'trastero'],
  }),
];
