/** Categoría PERSONAJES — quién es quién en el portal. Contenido DEMO. */

import { imp, mc, tf, who } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

export const PERSONAJES_QUESTIONS: QuestionRecord[] = [
  who({
    id: 'per-who-amancio',
    prompt: '¿Quién es?',
    clues: [
      'Tiene una garita con un calendario de 1998 colgado',
      'Lleva más de treinta años en el mismo puesto',
      'Su felpudo es intocable',
      'Es el portero del edificio',
    ],
    options: ['Amancio Quintela', 'Braulio Quiles', 'Yeyo', 'Vichi Nadal'],
    correct: 0,
    difficulty: 3,
    category: 'personajes',
    explanation: 'Amancio Quintela, portero, treinta y un años y un calendario que no piensa cambiar.',
    characters: [N.amancio],
    tags: ['portero'],
  }),
  who({
    id: 'per-who-charo',
    prompt: '¿Quién es?',
    clues: [
      'Siempre lleva una carpeta de tapas rojas',
      'Convoca las juntas y las sufre',
      'Vive en el 4ºA',
      'Es la presidenta de la comunidad desde 2019',
    ],
    options: ['Charo Peláez', 'Loli Tabares', 'Puri Bocanegra', 'Merche Roldán'],
    correct: 0,
    difficulty: 3,
    category: 'personajes',
    explanation: 'Charo Peláez, presidenta, 4ºA, carpeta roja.',
    characters: [N.charo],
    tags: ['junta'],
  }),
  who({
    id: 'per-who-braulio',
    prompt: '¿Quién es?',
    clues: [
      'Tiene tres bicicletas en el rellano',
      'Vive en el bajo C',
      'Pide que conste en acta su desacuerdo',
      'Vota no a todas las derramas',
    ],
    options: ['Braulio Quiles', 'Amancio Quintela', 'Tino Palomeque', 'Ramiro Cifuentes'],
    correct: 0,
    difficulty: 4,
    category: 'personajes',
    explanation: 'Braulio Quiles, bajo C, oposición permanente y flota de bicicletas.',
    characters: [N.braulio],
    tags: ['junta'],
  }),
  who({
    id: 'per-who-nieves',
    prompt: '¿Quién es?',
    clues: [
      'Corrige la ortografía de los carteles del tablón',
      'Da clases particulares en su salón',
      'Su gata se llama Pelusa',
      'Es profesora de latín jubilada y vive en el 1ºA',
    ],
    options: ['Nieves Arrondo', 'Doña Fefa Marín', 'Sagrario Bocanegra', 'Chusa Vega'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Nieves Arrondo, 1ºA, latín, y una gata con vocación de fugitiva.',
    characters: [N.nieves],
    tags: ['pelusa'],
  }),
  who({
    id: 'per-who-kevin',
    prompt: '¿Quién es?',
    clues: [
      'Aparca donde no debe',
      'Todo el portal le pide favores de última hora',
      'Trabaja repartiendo paquetes',
      'Vive en el 1ºB y tiene veinticuatro años',
    ],
    options: ['Kevin Salgado', 'Yeyo', 'Tino Palomeque', 'Vichi Nadal'],
    correct: 0,
    difficulty: 4,
    category: 'personajes',
    explanation: 'Kevin Salgado, 1ºB, repartidor y aparcamiento creativo.',
    characters: [N.kevin],
    tags: ['paquetes'],
  }),
  who({
    id: 'per-who-fefa',
    prompt: '¿Quién es?',
    clues: [
      'Delegó su voto por escrito y decidió una derrama',
      'Vive en el edificio desde 1971',
      'Tiene noventa y dos años',
      'Vive en el 3ºB y lo ha visto absolutamente todo',
    ],
    options: ['Doña Fefa Marín', 'Nieves Arrondo', 'Puri Bocanegra', 'Charo Peláez'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Doña Fefa Marín, 3ºB, desde 1971 y con voto decisivo.',
    characters: [N.fefa],
    season: 1,
    tags: ['veteranos'],
  }),
  who({
    id: 'per-who-vichi',
    prompt: '¿Quién es?',
    clues: [
      'Se le oye mejor en el 3ºB que en su propia casa',
      'Puso un repetidor de WiFi en la escalera',
      'Ensaya a las tres de la madrugada',
      'Es músico, toca el bajo y vive en el 4ºB',
    ],
    options: ['Vichi Nadal', 'Yeyo', 'Kevin Salgado', 'Braulio Quiles'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Vichi Nadal, 4ºB, bajista nocturno y técnico de redes aficionado.',
    characters: [N.vichi],
    season: 4,
    tags: ['ruido', 'wifi'],
  }),
  who({
    id: 'per-who-loli',
    prompt: '¿Quién es?',
    clues: [
      'No vive en el edificio pero decide bastante',
      'Los viernes es imposible localizarla',
      'Firma las circulares que aparecen en el tablón',
      'Lleva la administración de la finca',
    ],
    options: ['Loli Tabares', 'Charo Peláez', 'Susi Berrocal', 'Merche Roldán'],
    correct: 0,
    difficulty: 6,
    category: 'personajes',
    explanation: 'Loli Tabares, de Fincas Tabares. Contestador automático desde el jueves por la tarde.',
    characters: [N.loli],
    tags: ['administración'],
  }),
  who({
    id: 'per-who-susi',
    prompt: '¿Quién es?',
    clues: [
      'Sabe lo que desayuna cada vecino',
      'Trabaja en el bajo comercial',
      'Guarda paquetes cuando no hay nadie en la portería',
      'Regenta el Bar Los Faroles',
    ],
    options: ['Susi Berrocal', 'Puri Bocanegra', 'Chusa Vega', 'Nieves Arrondo'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Susi Berrocal, Bar Los Faroles, archivo oral de la comunidad.',
    characters: [N.susi],
    tags: ['bar'],
  }),
  who({
    id: 'per-who-yeyo',
    prompt: '¿Quién es?',
    clues: [
      'Aparece siempre con una llave Allen',
      'Es familia de alguien del portal',
      'Dice que el ascensor "ya está" seis veces al año',
      'Es el sobrino del portero',
    ],
    options: ['Yeyo', 'Kevin Salgado', 'Tino Palomeque', 'Ramiro Cifuentes'],
    correct: 0,
    difficulty: 6,
    category: 'personajes',
    explanation: 'Yeyo, sobrino de Amancio y "técnico" oficial del ascensor.',
    characters: [N.yeyo, N.amancio],
    tags: ['ascensor'],
  }),
  who({
    id: 'per-who-hermanas',
    prompt: '¿Quiénes son?',
    clues: [
      'Se reparten el turno de vigilancia del patio',
      'Viven en el 2ºB',
      'Tienen una silla estratégicamente colocada',
      'Son las hermanas que sostienen Radio Patio',
    ],
    options: ['Puri y Sagrario Bocanegra', 'Los Tremiño', 'Tino y Merche', 'Ramiro y Chusa'],
    correct: 0,
    difficulty: 4,
    category: 'personajes',
    explanation: 'Puri y Sagrario Bocanegra, 2ºB, turnos de mañana y tarde.',
    characters: [N.puri, N.sagrario],
    tags: ['radio-patio'],
  }),
  who({
    id: 'per-who-ramiro',
    prompt: '¿Quién es?',
    clues: [
      'Su vivienda está en obras desde hace catorce meses',
      'Dice que "ya casi está"',
      'Vive en el 2ºA con su pareja',
      'Es el responsable de la gotera del primero',
    ],
    options: ['Ramiro Cifuentes', 'Braulio Quiles', 'Tino Palomeque', 'Kevin Salgado'],
    correct: 0,
    difficulty: 6,
    category: 'personajes',
    explanation: 'Ramiro Cifuentes, 2ºA, catorce meses de obra y una gotera de propina.',
    characters: [N.ramiro, N.chusa],
    season: 2,
    tags: ['obras'],
  }),
  mc({
    id: 'per-mc-piso-charo',
    prompt: '¿En qué piso vive Charo Peláez?',
    options: ['4ºA', '2ºB', '1ºA', 'Bajo C'],
    correct: 0,
    difficulty: 4,
    category: 'personajes',
    explanation: '4ºA. Desde ahí controla el rellano y media escalera.',
    characters: [N.charo],
  }),
  mc({
    id: 'per-mc-piso-fefa',
    prompt: '¿Quién vive en el 3ºB?',
    options: ['Doña Fefa Marín', 'Vichi Nadal', 'Kevin Salgado', 'Nieves Arrondo'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Doña Fefa Marín, desde 1971.',
    characters: [N.fefa],
  }),
  mc({
    id: 'per-mc-oficio-nieves',
    prompt: '¿A qué se dedicaba Nieves Arrondo antes de jubilarse?',
    options: ['Profesora de latín', 'Enfermera', 'Peluquera', 'Funcionaria de Hacienda'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Profesora de latín. De ahí que corrija los carteles del tablón.',
    characters: [N.nieves],
  }),
  mc({
    id: 'per-mc-pareja-tino',
    prompt: '¿Con quién vive Tino Palomeque en el 3ºA?',
    options: ['Merche Roldán', 'Chusa Vega', 'Sagrario Bocanegra', 'Susi Berrocal'],
    correct: 0,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Con Merche Roldán. Recién casados y con un mueble a medio montar.',
    characters: [N.tino, N.merche],
  }),
  mc({
    id: 'per-mc-bicicletas',
    prompt: '¿Cuántas bicicletas tiene Braulio Quiles en el rellano?',
    options: ['Tres', 'Una', 'Dos', 'Cinco'],
    correct: 0,
    difficulty: 7,
    category: 'personajes',
    explanation: 'Tres, y ninguna funciona. Pero son suyas y están en su rellano.',
    characters: [N.braulio],
  }),
  mc({
    id: 'per-mc-edad-kevin',
    prompt: '¿Qué edad tiene Kevin Salgado?',
    options: ['24', '31', '19', '40'],
    correct: 0,
    difficulty: 8,
    category: 'personajes',
    explanation: 'Veinticuatro. Y una moto que ya conoce el portal mejor que él.',
    characters: [N.kevin],
  }),
  mc({
    id: 'per-mc-quien-atico',
    prompt: '¿Quién vive en el ático?',
    options: ['Los Tremiño', 'Doña Fefa Marín', 'Vichi Nadal', 'Nadie, es un trastero'],
    correct: 0,
    difficulty: 6,
    category: 'personajes',
    explanation: 'Los Tremiño. En teoría. En la práctica, sus macetas.',
    characters: [N.tremino],
  }),
  mc({
    id: 'per-mc-quien-4b',
    prompt: '¿Quién vive en el 4ºB?',
    options: ['Vichi Nadal', 'Charo Peláez', 'Braulio Quiles', 'Los Tremiño'],
    correct: 0,
    difficulty: 6,
    category: 'personajes',
    explanation: 'Vichi Nadal, con su bajo y su horario invertido.',
    characters: [N.vichi],
  }),
  mc({
    id: 'per-mc-quien-bajoA',
    prompt: '¿Quién ocupa el bajo A?',
    options: ['Susi Berrocal', 'Braulio Quiles', 'Kevin Salgado', 'Amancio Quintela'],
    correct: 0,
    difficulty: 7,
    category: 'personajes',
    explanation: 'Susi Berrocal, que además lleva el bar del bajo comercial.',
    characters: [N.susi],
  }),
  mc({
    id: 'per-mc-turnos-hermanas',
    prompt: '¿Cómo se reparten las hermanas Bocanegra la vigilancia del patio?',
    options: [
      'Puri por la mañana y Sagrario por la tarde',
      'Las dos a la vez, siempre',
      'Se turnan por semanas',
      'Solo vigilan los domingos',
    ],
    correct: 0,
    difficulty: 8,
    category: 'personajes',
    explanation: 'Turno de mañana para Puri, turno de tarde para Sagrario. Radio Patio no cierra.',
    characters: [N.puri, N.sagrario],
  }),
  mc({
    id: 'per-mc-herramienta-yeyo',
    prompt: '¿Con qué herramienta arregla Yeyo el ascensor?',
    options: ['Una llave Allen', 'Un martillo', 'Un destornillador de estrella', 'Un multímetro'],
    correct: 0,
    difficulty: 7,
    category: 'personajes',
    explanation: 'Una llave Allen y mucha seguridad en sí mismo.',
    characters: [N.yeyo],
  }),
  mc({
    id: 'per-mc-carpeta',
    prompt: '¿De qué color es la carpeta con la que Charo lleva las juntas?',
    options: ['Roja', 'Azul', 'Verde', 'Negra'],
    correct: 0,
    difficulty: 8,
    category: 'personajes',
    explanation: 'Tapas rojas. Si la carpeta sale del 4ºA, hay junta.',
    characters: [N.charo],
  }),
  tf({
    id: 'per-tf-nieves-carteles',
    prompt: 'Nieves Arrondo corrige la ortografía de los carteles del tablón.',
    answer: true,
    difficulty: 4,
    category: 'personajes',
    explanation: 'Con bolígrafo rojo y sin pedir permiso.',
    characters: [N.nieves],
  }),
  tf({
    id: 'per-tf-amancio-sobrino',
    prompt: 'Yeyo es sobrino de Amancio Quintela.',
    answer: true,
    difficulty: 4,
    category: 'personajes',
    explanation: 'De ahí que tenga llave del cuarto de máquinas.',
    characters: [N.yeyo, N.amancio],
  }),
  tf({
    id: 'per-tf-susi-vecina',
    prompt: 'Susi Berrocal solo trabaja en el portal, no vive en él.',
    answer: false,
    difficulty: 6,
    category: 'personajes',
    explanation: 'Vive en el bajo A y trabaja en el bajo comercial. Cero desplazamiento.',
    characters: [N.susi],
  }),
  tf({
    id: 'per-tf-charo-administradora',
    prompt: 'Charo Peláez es, además de presidenta, la administradora de la finca.',
    answer: false,
    difficulty: 5,
    category: 'personajes',
    explanation: 'La administradora es Loli Tabares. Charo solo presidenta, que ya es bastante.',
    characters: [N.charo, N.loli],
  }),
  tf({
    id: 'per-tf-tino-merche-recien',
    prompt: 'Tino y Merche son los recién casados del portal.',
    answer: true,
    difficulty: 3,
    category: 'personajes',
    explanation: 'Recién casados y en plena fase de montar muebles.',
    characters: [N.tino, N.merche],
  }),
  imp({
    id: 'per-imp-tercero',
    prompt: 'Tres viven en una tercera planta o más arriba. ¿Quién es el infiltrado?',
    setLabel: 'Vecinos de plantas altas',
    items: ['Doña Fefa Marín', 'Charo Peláez', 'Vichi Nadal', 'Nieves Arrondo'],
    impostor: 3,
    difficulty: 7,
    category: 'personajes',
    explanation: 'Nieves vive en el 1ºA. Los otros tres, del tercero para arriba.',
    characters: [N.nieves],
  }),
  imp({
    id: 'per-imp-no-vecinos',
    prompt: 'Tres NO son propietarios del edificio. ¿Cuál se ha colado?',
    setLabel: 'Gente que anda por el portal sin ser propietaria',
    items: ['Loli Tabares', 'Yeyo', 'Kevin Salgado', 'Amancio Quintela'],
    impostor: 2,
    difficulty: 8,
    category: 'personajes',
    explanation: 'Kevin vive en el 1ºB. La administradora, el sobrino y el portero no son propietarios.',
    characters: [N.kevin],
  }),
  imp({
    id: 'per-imp-radio-patio',
    prompt: 'Tres alimentan Radio Patio. ¿Cuál no suelta nunca prenda?',
    setLabel: 'Fuentes habituales de Radio Patio',
    items: ['Puri Bocanegra', 'Sagrario Bocanegra', 'Susi Berrocal', 'Los Tremiño'],
    impostor: 3,
    difficulty: 5,
    category: 'personajes',
    explanation: 'Los Tremiño no cuentan nada porque no están nunca.',
    characters: [N.tremino],
  }),
];
