/** Categoría SITUACIONES — derramas, obras, ruidos y malentendidos. Contenido DEMO. */

import { bet, imp, mc, ord, tf } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

export const SITUACIONES_QUESTIONS: QuestionRecord[] = [
  mc({
    id: 'sit-mc-derrama-motivo',
    prompt: '¿Para qué era la primera derrama de la comunidad?',
    options: ['Arreglar el ascensor', 'Pintar el portal', 'Cambiar los buzones', 'Poner cámaras'],
    correct: 0,
    difficulty: 3,
    category: 'situaciones',
    explanation: 'Para el ascensor, que ya se paraba antes pero con menos ceremonia.',
    season: 1,
    tags: ['derrama', 'ascensor'],
  }),
  mc({
    id: 'sit-mc-gotera-origen',
    prompt: '¿De dónde venía la gotera del 1ºA?',
    options: ['De las obras del 2ºA', 'De la azotea', 'Del patio de luces', 'Del cuarto de contadores'],
    correct: 0,
    difficulty: 5,
    category: 'situaciones',
    explanation: 'De las obras de Ramiro y Chusa. Tardó cuatro meses en admitirse.',
    characters: [N.nieves, N.ramiro, N.chusa],
    season: 2,
    tags: ['obras', 'gotera'],
  }),
  mc({
    id: 'sit-mc-veces-ascensor',
    prompt: '¿Cuántas veces al año "arregla" Yeyo el ascensor?',
    options: ['Seis', 'Una', 'Tres', 'Doce'],
    correct: 0,
    difficulty: 7,
    category: 'situaciones',
    explanation: 'Seis. Y en las seis dice que ya está.',
    characters: [N.yeyo],
    tags: ['ascensor'],
  }),
  mc({
    id: 'sit-mc-hora-bajo',
    prompt: '¿A qué hora ensaya Vichi con el bajo?',
    options: ['A las tres de la madrugada', 'A las nueve de la mañana', 'A la hora de comer', 'Los domingos por la tarde'],
    correct: 0,
    difficulty: 4,
    category: 'situaciones',
    explanation: 'A las tres. Cuando el patio de luces está más receptivo.',
    characters: [N.vichi],
    tags: ['ruido'],
  }),
  mc({
    id: 'sit-mc-duracion-junta',
    prompt: '¿Cuánto dura la junta ordinaria de julio?',
    options: ['Cuatro horas', 'Media hora', 'Hora y media', 'Dos días'],
    correct: 0,
    difficulty: 4,
    category: 'situaciones',
    explanation: 'Cuatro horas. Tres de ellas hablando del ascensor.',
    characters: [N.charo],
    tags: ['junta'],
  }),
  mc({
    id: 'sit-mc-obras-meses',
    prompt: '¿Cuánto llevan las obras del 2ºA?',
    options: ['Catorce meses', 'Tres semanas', 'Seis meses', 'Cuatro años'],
    correct: 0,
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Catorce meses. Y una lona en el balcón que ya es parte de la fachada.',
    characters: [N.ramiro, N.chusa],
    season: 2,
    tags: ['obras'],
  }),
  mc({
    id: 'sit-mc-raya-garaje',
    prompt: '¿Qué hizo Braulio cuando la moto de Kevin apareció en la plaza 7?',
    options: ['Pintó una raya en el suelo', 'Llamó a la grúa', 'Le pinchó una rueda', 'Convocó una manifestación'],
    correct: 0,
    difficulty: 6,
    category: 'situaciones',
    explanation: 'Una raya blanca, a mano alzada, con pintura de la comunidad.',
    characters: [N.braulio, N.kevin],
    season: 5,
    tags: ['garaje'],
  }),
  mc({
    id: 'sit-mc-pelusa-dias',
    prompt: '¿Cuántos días estuvo desaparecida Pelusa?',
    options: ['Siete', 'Dos', 'Quince', 'Un mes'],
    correct: 0,
    difficulty: 6,
    category: 'situaciones',
    explanation: 'Siete días. Con carteles en el tablón corregidos por su propia dueña.',
    characters: [N.nieves],
    season: 3,
    tags: ['pelusa'],
  }),
  mc({
    id: 'sit-mc-wifi-solucion',
    prompt: '¿Cómo se resolvió la mala cobertura del WiFi comunitario?',
    options: [
      'Vichi puso un repetidor en la escalera',
      'Se cambió de compañía',
      'Se subió la antena al ático',
      'No se resolvió',
    ],
    correct: 0,
    difficulty: 7,
    category: 'situaciones',
    explanation: 'Un repetidor enchufado en la escalera, con un cable que cruza el rellano.',
    characters: [N.vichi],
    season: 4,
    tags: ['wifi'],
  }),
  tf({
    id: 'sit-tf-ascensor-primero',
    prompt: 'La primera vez que se habló del ascensor en junta fue en la primera temporada.',
    answer: true,
    difficulty: 4,
    category: 'situaciones',
    explanation: 'Y la segunda, y la tercera. El punto del orden del día es prácticamente fijo.',
    season: 1,
    tags: ['ascensor', 'junta'],
  }),
  tf({
    id: 'sit-tf-braulio-derrama-paga',
    prompt: 'Braulio acabó pagando la derrama del ascensor pese a votar en contra.',
    answer: true,
    difficulty: 6,
    category: 'situaciones',
    explanation: 'La pagó, pero pidió que constara que la pagaba en contra.',
    characters: [N.braulio],
    season: 1,
    tags: ['derrama'],
  }),
  tf({
    id: 'sit-tf-obras-permiso',
    prompt: 'Ramiro pidió permiso a la comunidad antes de empezar las obras.',
    answer: false,
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Empezó un martes a las ocho de la mañana. El permiso llegó después, por escrito y con retraso.',
    characters: [N.ramiro],
    season: 2,
    tags: ['obras'],
  }),
  tf({
    id: 'sit-tf-pelusa-trastero',
    prompt: 'Pelusa apareció en el trastero 4.',
    answer: true,
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Entre las sillas plegables de la comunidad, tan tranquila.',
    characters: [N.nieves],
    season: 3,
    tags: ['pelusa'],
  }),
  tf({
    id: 'sit-tf-moto-portal-permitida',
    prompt: 'La junta autorizó que Kevin dejase la moto en el portal.',
    answer: false,
    difficulty: 6,
    category: 'situaciones',
    explanation: 'Se prohibió por escrito. La moto sigue ahí. Ambas cosas son verdad.',
    characters: [N.kevin],
    tags: ['portal'],
  }),
  tf({
    id: 'sit-tf-amancio-jubilacion',
    prompt: 'Amancio amenaza con jubilarse en todas las juntas.',
    answer: true,
    difficulty: 4,
    category: 'situaciones',
    explanation: 'Y en todas se le convence en menos de diez minutos.',
    characters: [N.amancio],
    tags: ['portero', 'junta'],
  }),
  tf({
    id: 'sit-tf-antena-caida',
    prompt: 'La antena de la azotea se cayó durante una tormenta.',
    answer: false,
    difficulty: 7,
    category: 'situaciones',
    explanation: 'No se cayó: se torció. Y así se quedó, con las dos bridas originales.',
    season: 4,
    tags: ['antena'],
  }),
  tf({
    id: 'sit-tf-tino-mueble',
    prompt: 'Tino y Merche discutieron por montar un mueble.',
    answer: true,
    difficulty: 3,
    category: 'situaciones',
    explanation: 'Y se oyó en el patio de luces, con instrucciones y todo.',
    characters: [N.tino, N.merche],
    tags: ['ruido'],
  }),
  imp({
    id: 'sit-imp-junta',
    prompt: 'Tres cosas pasan en toda junta del portal. ¿Cuál no pasa nunca?',
    setLabel: 'Cosas que pasan en las juntas',
    items: [
      'Braulio vota en contra',
      'Se habla del ascensor',
      'Charo reparte fotocopias',
      'La junta acaba antes de lo previsto',
    ],
    impostor: 3,
    difficulty: 4,
    category: 'situaciones',
    explanation: 'Ninguna junta ha acabado antes de lo previsto. Ninguna.',
    characters: [N.braulio, N.charo],
    tags: ['junta'],
  }),
  imp({
    id: 'sit-imp-excusas',
    prompt: 'Tres son excusas reales oídas en el portal para no pagar la derrama. ¿Cuál se ha colado?',
    setLabel: 'Excusas para no pagar la derrama',
    items: [
      '"Yo no uso el ascensor"',
      '"Eso ya lo pagué en 2011"',
      '"A mí nadie me avisó"',
      '"Estoy de acuerdo, tomad el dinero"',
    ],
    impostor: 3,
    difficulty: 3,
    category: 'situaciones',
    explanation: 'Nadie ha dicho nunca la cuarta. Sería motivo de junta extraordinaria.',
    tags: ['derrama'],
  }),
  imp({
    id: 'sit-imp-ruidos-nocturnos',
    prompt: 'Tres ruidos son de madrugada. ¿Cuál es diurno?',
    setLabel: 'Ruidos nocturnos del portal',
    items: ['El bajo de Vichi', 'La moto de Kevin al llegar', 'El ascensor parándose', 'La radial del 2ºA'],
    impostor: 3,
    difficulty: 6,
    category: 'situaciones',
    explanation: 'La radial es de las ocho de la mañana, que para eso hay normativa.',
    characters: [N.vichi, N.kevin, N.ramiro],
  }),
  imp({
    id: 'sit-imp-cosas-tablon',
    prompt: 'Tres cosas han estado colgadas en el tablón. ¿Cuál no?',
    setLabel: 'Cosas colgadas en el tablón',
    items: [
      'Carteles de Pelusa desaparecida',
      'La contraseña del WiFi',
      'Circular sobre la moto del portal',
      'El acta original de 1971',
    ],
    impostor: 3,
    difficulty: 7,
    category: 'situaciones',
    explanation: 'El acta de 1971 no ha salido nunca del archivo de Fincas Tabares.',
    characters: [N.loli],
  }),
  ord({
    id: 'sit-ord-derrama',
    prompt: 'Ordena cómo se aprobó la derrama del ascensor.',
    steps: [
      'El ascensor se queda parado con dos vecinos dentro',
      'Charo convoca junta extraordinaria',
      'Braulio propone esperar "a ver si se arregla solo"',
      'Doña Fefa delega su voto por escrito',
      'La derrama se aprueba por un voto',
    ],
    difficulty: 7,
    category: 'situaciones',
    explanation: 'Cinco pasos y 2.400 €.',
    characters: [N.charo, N.braulio, N.fefa],
    season: 1,
    tags: ['derrama'],
  }),
  ord({
    id: 'sit-ord-gotera',
    prompt: 'Ordena el caso de la gotera del primero.',
    steps: [
      'Aparece una mancha en el techo de Nieves',
      'Ramiro asegura que su obra no tiene nada que ver',
      'Loli manda un técnico que tarda tres semanas',
      'Se confirma que viene del 2ºA',
    ],
    difficulty: 6,
    category: 'situaciones',
    explanation: 'La mancha creció más rápido que la voluntad de admitirlo.',
    characters: [N.nieves, N.ramiro, N.loli],
    season: 2,
    tags: ['gotera'],
  }),
  ord({
    id: 'sit-ord-pelusa',
    prompt: 'Ordena la búsqueda de Pelusa.',
    steps: [
      'Nieves nota que la ventana del patio está abierta',
      'Se cuelgan carteles en el tablón',
      'Radio Patio informa de un maullido en el sótano',
      'Amancio abre el trastero 4 y ahí está',
    ],
    difficulty: 5,
    category: 'situaciones',
    explanation: 'Siete días de operación vecinal con final feliz.',
    characters: [N.nieves, N.amancio],
    season: 3,
    tags: ['pelusa'],
  }),
  ord({
    id: 'sit-ord-wifi',
    prompt: 'Ordena la crisis del WiFi comunitario.',
    steps: [
      'El WiFi deja de llegar al cuarto piso',
      'Se acusa a la antena de la azotea',
      'Vichi enchufa un repetidor en la escalera',
      'Alguien desenchufa el repetidor para aspirar el rellano',
    ],
    difficulty: 8,
    category: 'situaciones',
    explanation: 'Y volvimos al punto de partida, como en toda buena comunidad.',
    characters: [N.vichi],
    season: 4,
    tags: ['wifi'],
  }),
  bet({
    id: 'sit-bet-gotera',
    prompt: 'Apuesta final: ¿cuánto tardó el técnico de la administradora en venir a ver la gotera?',
    options: ['Tres semanas', 'Dos días', 'Cuatro meses', 'No vino nunca'],
    correct: 0,
    difficulty: 9,
    category: 'situaciones',
    explanation: 'Tres semanas. Y luego dijo que había que llamar a otro técnico.',
    characters: [N.loli],
    season: 2,
    tags: ['final', 'gotera'],
  }),
  bet({
    id: 'sit-bet-obras',
    prompt: '¿Qué día de la semana empezaron las obras del 2ºA?',
    options: ['Un martes', 'Un lunes', 'Un sábado', 'Un domingo'],
    correct: 0,
    difficulty: 9,
    category: 'situaciones',
    explanation: 'Un martes a las ocho, sin avisar y con radial.',
    characters: [N.ramiro],
    season: 2,
    tags: ['final', 'obras'],
  }),
];
