/** Categoría TEMPORADAS — qué pasó y cuándo, en la crónica del portal. Contenido DEMO. */

import { bet, mc, ord, tf } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

export const TEMPORADAS_QUESTIONS: QuestionRecord[] = [
  mc({
    id: 'tem-mc-t1',
    prompt: '¿Qué trama marcó la primera temporada del portal?',
    options: ['La derrama del ascensor', 'La gotera del primero', 'La antena de la azotea', 'La plaza 7'],
    correct: 0,
    difficulty: 3,
    category: 'temporadas',
    explanation: 'Temporada 1: la derrama del ascensor, 2.400 € y un voto de diferencia.',
    season: 1,
    tags: ['derrama'],
  }),
  mc({
    id: 'tem-mc-t2',
    prompt: '¿Y la segunda temporada?',
    options: ['La gotera del primero', 'La desaparición de Pelusa', 'El WiFi comunitario', 'La derrama del ascensor'],
    correct: 0,
    difficulty: 4,
    category: 'temporadas',
    explanation: 'Temporada 2: la gotera del 1ºA, cortesía de las obras del 2ºA.',
    season: 2,
    tags: ['gotera'],
  }),
  mc({
    id: 'tem-mc-t3',
    prompt: '¿Qué ocurrió en la tercera temporada?',
    options: ['Desapareció Pelusa', 'Se torció la antena', 'Se pintó la raya del garaje', 'Se aprobó la derrama'],
    correct: 0,
    difficulty: 4,
    category: 'temporadas',
    explanation: 'Temporada 3: siete días sin Pelusa y un portal entero movilizado.',
    characters: [N.nieves],
    season: 3,
    tags: ['pelusa'],
  }),
  mc({
    id: 'tem-mc-t4',
    prompt: '¿Cuál es la trama principal de la cuarta temporada?',
    options: ['La antena y el WiFi', 'La plaza 7', 'La gotera', 'La jubilación del portero'],
    correct: 0,
    difficulty: 5,
    category: 'temporadas',
    explanation: 'Temporada 4: antena torcida, bridas y repetidor en la escalera.',
    characters: [N.vichi, N.yeyo],
    season: 4,
    tags: ['wifi', 'antena'],
  }),
  mc({
    id: 'tem-mc-t5',
    prompt: '¿Con qué conflicto arranca la quinta temporada?',
    options: ['La plaza 7 del garaje', 'La derrama del ascensor', 'La gotera del primero', 'El paquete sin destinatario'],
    correct: 0,
    difficulty: 5,
    category: 'temporadas',
    explanation: 'Temporada 5: la moto, la raya y la junta extraordinaria.',
    characters: [N.kevin, N.braulio],
    season: 5,
    tags: ['garaje'],
  }),
  mc({
    id: 'tem-mc-orden-tramas',
    prompt: '¿Qué trama es POSTERIOR a la desaparición de Pelusa?',
    options: ['La antena y el WiFi', 'La derrama del ascensor', 'La gotera del primero', 'Ninguna'],
    correct: 0,
    difficulty: 6,
    category: 'temporadas',
    explanation: 'Pelusa es de la tercera; la antena y el WiFi, de la cuarta.',
    season: 4,
  }),
  mc({
    id: 'tem-mc-temporada-derrama',
    prompt: '¿En qué temporada se aprobó la derrama de 2.400 €?',
    options: ['En la primera', 'En la segunda', 'En la cuarta', 'En la quinta'],
    correct: 0,
    difficulty: 5,
    category: 'temporadas',
    explanation: 'Primera temporada, y todavía se recuerda en cada junta.',
    season: 1,
    tags: ['derrama'],
  }),
  mc({
    id: 'tem-mc-temporada-obras-inicio',
    prompt: '¿En qué temporada empezaron las obras del 2ºA?',
    options: ['En la segunda', 'En la primera', 'En la tercera', 'En la quinta'],
    correct: 0,
    difficulty: 6,
    category: 'temporadas',
    explanation: 'Segunda temporada. Y siguen abiertas, temporada tras temporada.',
    characters: [N.ramiro],
    season: 2,
    tags: ['obras'],
  }),
  tf({
    id: 'tem-tf-t1-ascensor',
    prompt: 'La primera temporada gira alrededor del ascensor.',
    answer: true,
    difficulty: 3,
    category: 'temporadas',
    explanation: 'El ascensor es el protagonista involuntario de toda la crónica.',
    season: 1,
  }),
  tf({
    id: 'tem-tf-t3-antena',
    prompt: 'La antena de la azotea se torció en la tercera temporada.',
    answer: false,
    difficulty: 6,
    category: 'temporadas',
    explanation: 'Fue en la cuarta. En la tercera lo importante era Pelusa.',
    season: 4,
  }),
  tf({
    id: 'tem-tf-t5-garaje',
    prompt: 'La quinta temporada incluye una junta extraordinaria por el garaje.',
    answer: true,
    difficulty: 4,
    category: 'temporadas',
    explanation: 'Con la raya blanca ya pintada y la moto sin moverse.',
    season: 5,
    tags: ['garaje'],
  }),
  tf({
    id: 'tem-tf-charo-t1',
    prompt: 'Charo ya era presidenta en la primera temporada.',
    answer: true,
    difficulty: 7,
    category: 'temporadas',
    explanation: 'Presidenta desde 2019, con la carpeta roja incluida desde el principio.',
    characters: [N.charo],
    season: 1,
  }),
  tf({
    id: 'tem-tf-pelusa-t2',
    prompt: 'Pelusa desapareció en la segunda temporada.',
    answer: false,
    difficulty: 5,
    category: 'temporadas',
    explanation: 'Tercera. La segunda fue la de la gotera.',
    characters: [N.nieves],
    season: 3,
    tags: ['pelusa'],
  }),
  tf({
    id: 'tem-tf-cinco-temporadas',
    prompt: 'La crónica del portal tiene cinco temporadas.',
    answer: true,
    difficulty: 3,
    category: 'temporadas',
    explanation: 'Cinco: derrama, gotera, Pelusa, antena y plaza 7.',
  }),
  ord({
    id: 'tem-ord-temporadas',
    prompt: 'Ordena las cinco temporadas del portal.',
    steps: [
      'La derrama del ascensor',
      'La gotera del primero',
      'Pelusa no aparece',
      'La antena y el WiFi',
      'La plaza 7',
    ],
    difficulty: 5,
    category: 'temporadas',
    explanation: 'Ese es el orden oficial de la crónica del portal.',
    tags: ['temporadas'],
  }),
  ord({
    id: 'tem-ord-tres-primeras',
    prompt: 'Ordena estos tres momentos de la historia de la comunidad.',
    steps: [
      'Se aprueba la derrama del ascensor',
      'Empiezan las obras del 2ºA',
      'Aparece Pelusa en el trastero 4',
    ],
    difficulty: 4,
    category: 'temporadas',
    explanation: 'Temporadas 1, 2 y 3, en ese orden.',
    tags: ['temporadas'],
  }),
  ord({
    id: 'tem-ord-ultimas',
    prompt: 'Ordena los hechos de las dos últimas temporadas.',
    steps: [
      'La antena aparece torcida',
      'Vichi enchufa el repetidor',
      'Kevin aparca en la plaza 7',
      'Se convoca la junta extraordinaria del garaje',
    ],
    difficulty: 7,
    category: 'temporadas',
    explanation: 'Cuarta y quinta temporada, en secuencia.',
    characters: [N.vichi, N.kevin],
    tags: ['temporadas'],
  }),
  bet({
    id: 'tem-bet-temporada-wifi',
    prompt: 'Apuesta final: ¿en qué temporada se instaló el repetidor de WiFi?',
    options: ['En la cuarta', 'En la tercera', 'En la quinta', 'En la segunda'],
    correct: 0,
    difficulty: 8,
    category: 'temporadas',
    explanation: 'Cuarta temporada, y con cable cruzando el rellano.',
    characters: [N.vichi],
    season: 4,
    tags: ['final', 'wifi'],
  }),
  bet({
    id: 'tem-bet-titulo-t3',
    prompt: '¿Cómo se conoce la tercera temporada en el portal?',
    options: ['"Pelusa no aparece"', '"La gotera del primero"', '"La plaza 7"', '"La antena y el WiFi"'],
    correct: 0,
    difficulty: 7,
    category: 'temporadas',
    explanation: 'Siete días de búsqueda dan para bautizar una temporada.',
    characters: [N.nieves],
    season: 3,
    tags: ['final', 'pelusa'],
  }),
  bet({
    id: 'tem-bet-temporada-plaza',
    prompt: '¿En qué temporada se pintó la raya del garaje?',
    options: ['En la quinta', 'En la primera', 'En la cuarta', 'En la segunda'],
    correct: 0,
    difficulty: 7,
    category: 'temporadas',
    explanation: 'Quinta temporada, con pintura de la comunidad y sin permiso.',
    characters: [N.braulio],
    season: 5,
    tags: ['final', 'garaje'],
  }),
];
