/** Categoría TRAMAS — líos que duran varios capítulos. Contenido DEMO. */

import { bet, imp, mc, ord, who } from '../builders';
import { NEIGHBOURS as N } from '../portal';
import type { QuestionRecord } from '@/domain/questions/schemas';

export const TRAMAS_QUESTIONS: QuestionRecord[] = [
  ord({
    id: 'tra-ord-plaza7',
    prompt: 'Ordena la guerra de la plaza 7.',
    steps: [
      'Kevin aparca la moto en la plaza 7 "un ratito"',
      'Braulio pinta una raya blanca en el suelo',
      'Aparece una nota anónima en el buzón de Kevin',
      'Charo convoca junta extraordinaria',
      'Se acuerda que la moto suba al trastero y nadie cumple',
    ],
    difficulty: 8,
    category: 'tramas',
    explanation: 'Cinco pasos para no resolver nada. Récord del portal.',
    characters: [N.kevin, N.braulio, N.charo],
    season: 5,
    tags: ['garaje'],
  }),
  ord({
    id: 'tra-ord-antena',
    prompt: 'Ordena el asunto de la antena de la azotea.',
    steps: [
      'La señal de televisión empieza a fallar en las plantas altas',
      'Se sube a la azotea y se descubre la antena torcida',
      'Yeyo la sujeta con dos bridas',
      'Se aprueba en junta pagar un técnico que nunca se llama',
    ],
    difficulty: 7,
    category: 'tramas',
    explanation: 'Las bridas siguen ahí. Y funcionan, que es lo peor.',
    characters: [N.yeyo],
    season: 4,
    tags: ['antena'],
  }),
  ord({
    id: 'tra-ord-portero-jubilacion',
    prompt: 'Ordena el amago de jubilación de Amancio.',
    steps: [
      'Alguien mueve el felpudo de la garita',
      'Amancio anuncia que lo deja',
      'Medio portal baja a convencerlo',
      'Se queda, pero con condiciones por escrito',
    ],
    difficulty: 6,
    category: 'tramas',
    explanation: 'Las condiciones eran tres, y la primera era el felpudo.',
    characters: [N.amancio],
    tags: ['portero'],
  }),
  ord({
    id: 'tra-ord-obras',
    prompt: 'Ordena las obras eternas del 2ºA.',
    steps: [
      'Ramiro anuncia que son "dos semanitas"',
      'Aparece un contenedor de escombro en la puerta',
      'Se pasa del presupuesto y se para la obra tres meses',
      'La lona del balcón se convierte en parte del paisaje',
    ],
    difficulty: 6,
    category: 'tramas',
    explanation: 'Catorce meses después, la lona sigue ganando.',
    characters: [N.ramiro, N.chusa],
    season: 2,
    tags: ['obras'],
  }),
  ord({
    id: 'tra-ord-paquete-misterioso',
    prompt: 'Ordena la trama del paquete sin destinatario.',
    steps: [
      'Llega un paquete grande sin nombre',
      'Cada vecino jura que no es suyo',
      'Radio Patio decide que es del ático',
      'Los Tremiño no contestan al telefonillo',
      'Termina en el trastero 4 con los demás',
    ],
    difficulty: 7,
    category: 'tramas',
    explanation: 'El trastero 4 vuelve a hacer de archivo definitivo.',
    characters: [N.tremino, N.puri, N.sagrario],
    tags: ['paquetes'],
  }),
  ord({
    id: 'tra-ord-elecciones',
    prompt: 'Ordena cómo Charo acabó siendo presidenta.',
    steps: [
      'El presidente anterior anuncia que no repite',
      'Nadie levanta la mano durante cuatro minutos',
      'Charo dice "pues ya lo hago yo, pero un año"',
      'Sigue en el cargo desde 2019',
    ],
    difficulty: 7,
    category: 'tramas',
    explanation: 'Ese "un año" es la mentira más longeva del portal.',
    characters: [N.charo],
    tags: ['junta'],
  }),
  mc({
    id: 'tra-mc-nota-anonima',
    prompt: '¿Quién recibió una nota anónima en su buzón por el asunto de la plaza 7?',
    options: ['Kevin Salgado', 'Braulio Quiles', 'Charo Peláez', 'Amancio Quintela'],
    correct: 0,
    difficulty: 7,
    category: 'tramas',
    explanation: 'Kevin. Y todo el portal sabe quién la escribió, pero nadie lo dice.',
    characters: [N.kevin, N.braulio],
    season: 5,
    tags: ['garaje'],
  }),
  mc({
    id: 'tra-mc-condicion-felpudo',
    prompt: '¿Cuál fue la primera condición de Amancio para no jubilarse?',
    options: [
      'Que nadie toque su felpudo',
      'Que le suban el sueldo',
      'Que se cambie el ascensor',
      'Que Braulio deje de dejar bicicletas',
    ],
    correct: 0,
    difficulty: 6,
    category: 'tramas',
    explanation: 'El felpudo por delante de todo, incluso del sueldo.',
    characters: [N.amancio],
    tags: ['portero'],
  }),
  mc({
    id: 'tra-mc-obras-promesa',
    prompt: '¿Cuánto dijo Ramiro que durarían las obras?',
    options: ['Dos semanas', 'Dos meses', 'Un año', 'No dio plazo'],
    correct: 0,
    difficulty: 5,
    category: 'tramas',
    explanation: '"Dos semanitas". Iban por la semana sesenta.',
    characters: [N.ramiro],
    season: 2,
    tags: ['obras'],
  }),
  mc({
    id: 'tra-mc-tremino-teoria',
    prompt: 'Según Radio Patio, ¿por qué no aparecen nunca los Tremiño?',
    options: [
      'Porque tienen otra casa en la costa',
      'Porque están de obra en otra vivienda',
      'Porque se llevan mal con la presidenta',
      'Porque el ático no es suyo',
    ],
    correct: 0,
    difficulty: 8,
    category: 'tramas',
    explanation: 'Es la teoría oficial de Radio Patio. Sin ninguna prueba, como siempre.',
    characters: [N.tremino, N.puri, N.sagrario],
    tags: ['ático'],
  }),
  mc({
    id: 'tra-mc-voto-decisivo',
    prompt: '¿Quién emitió el voto que decidió la derrama del ascensor?',
    options: ['Doña Fefa Marín', 'Charo Peláez', 'Nieves Arrondo', 'Susi Berrocal'],
    correct: 0,
    difficulty: 6,
    category: 'tramas',
    explanation: 'Doña Fefa, por escrito, desde el 3ºB.',
    characters: [N.fefa],
    season: 1,
    tags: ['derrama'],
  }),
  mc({
    id: 'tra-mc-repetidor',
    prompt: '¿Qué le pasa al repetidor de WiFi de la escalera?',
    options: [
      'Que lo desenchufan para aspirar',
      'Que se lo llevó Vichi',
      'Que nunca se instaló',
      'Que se quemó en una tormenta',
    ],
    correct: 0,
    difficulty: 8,
    category: 'tramas',
    explanation: 'Un enchufe, dos usos y una guerra fría semanal.',
    characters: [N.vichi],
    season: 4,
    tags: ['wifi'],
  }),
  mc({
    id: 'tra-mc-junta-extra-motivo',
    prompt: '¿Qué motivó la junta extraordinaria de la quinta temporada?',
    options: ['La plaza 7 del garaje', 'La antena de la azotea', 'La gotera del primero', 'La gata desaparecida'],
    correct: 0,
    difficulty: 6,
    category: 'tramas',
    explanation: 'La plaza 7, la moto y una raya blanca.',
    season: 5,
    tags: ['garaje', 'junta'],
  }),
  mc({
    id: 'tra-mc-pelusa-aviso',
    prompt: '¿Quién dio la pista que llevó a encontrar a Pelusa?',
    options: ['Radio Patio', 'Loli Tabares', 'Kevin Salgado', 'Los Tremiño'],
    correct: 0,
    difficulty: 7,
    category: 'tramas',
    explanation: 'Las hermanas Bocanegra oyeron un maullido en el sótano. Por una vez, útil.',
    characters: [N.puri, N.sagrario],
    season: 3,
    tags: ['pelusa'],
  }),
  who({
    id: 'tra-who-culpable-gotera',
    prompt: '¿Quién es el responsable de la trama de la gotera?',
    clues: [
      'Jura que su obra no tiene nada que ver',
      'Vive justo encima de la afectada',
      'Prometió "dos semanitas" de obra',
      'Es el del 2ºA',
    ],
    options: ['Ramiro Cifuentes', 'Braulio Quiles', 'Vichi Nadal', 'Yeyo'],
    correct: 0,
    difficulty: 6,
    category: 'tramas',
    explanation: 'Ramiro Cifuentes, 2ºA, catorce meses y contando.',
    characters: [N.ramiro],
    season: 2,
    tags: ['gotera'],
  }),
  who({
    id: 'tra-who-raya',
    prompt: '¿Quién es el autor de la raya del garaje?',
    clues: [
      'Usó pintura de la comunidad sin pedirla',
      'Vive en el bajo',
      'Vota en contra de todo',
      'Tiene tres bicicletas en el rellano',
    ],
    options: ['Braulio Quiles', 'Amancio Quintela', 'Kevin Salgado', 'Tino Palomeque'],
    correct: 0,
    difficulty: 5,
    category: 'tramas',
    explanation: 'Braulio Quiles, bajo C, sección obras públicas.',
    characters: [N.braulio],
    season: 5,
    tags: ['garaje'],
  }),
  imp({
    id: 'tra-imp-temporada1',
    prompt: 'Tres cosas forman parte de la trama de la derrama. ¿Cuál se ha colado?',
    setLabel: 'Trama de la derrama del ascensor',
    items: [
      'El voto delegado de Doña Fefa',
      'Los 2.400 € del presupuesto',
      'La oposición de Braulio',
      'El repetidor de WiFi de la escalera',
    ],
    impostor: 3,
    difficulty: 5,
    category: 'tramas',
    explanation: 'El repetidor es de la trama del WiFi, dos temporadas más tarde.',
    season: 1,
    tags: ['derrama'],
  }),
  imp({
    id: 'tra-imp-plaza7',
    prompt: 'Tres cosas pasaron en la guerra de la plaza 7. ¿Cuál no?',
    setLabel: 'Guerra de la plaza 7',
    items: ['Una raya blanca', 'Una nota anónima', 'Una junta extraordinaria', 'Una denuncia en el juzgado'],
    impostor: 3,
    difficulty: 6,
    category: 'tramas',
    explanation: 'Se amenazó con el juzgado catorce veces. Nadie fue nunca.',
    season: 5,
    tags: ['garaje'],
  }),
  imp({
    id: 'tra-imp-pelusa',
    prompt: 'Tres cosas ocurrieron en la búsqueda de Pelusa. ¿Cuál se ha infiltrado?',
    setLabel: 'Búsqueda de Pelusa',
    items: [
      'Carteles en el tablón',
      'Un aviso de Radio Patio',
      'La apertura del trastero 4',
      'Un dron alquilado por la comunidad',
    ],
    impostor: 3,
    difficulty: 4,
    category: 'tramas',
    explanation: 'El dron lo propuso Yeyo y se rechazó por unanimidad, cosa rarísima.',
    characters: [N.yeyo],
    season: 3,
    tags: ['pelusa'],
  }),
  imp({
    id: 'tra-imp-obras',
    prompt: 'Tres son hitos de las obras del 2ºA. ¿Cuál no lo es?',
    setLabel: 'Obras eternas del 2ºA',
    items: [
      'El contenedor de escombro en la puerta',
      'La lona del balcón',
      'El parón de tres meses',
      'La instalación del ascensor nuevo',
    ],
    impostor: 3,
    difficulty: 5,
    category: 'tramas',
    explanation: 'El ascensor nunca se cambió: se arregló. Seis veces. Por Yeyo.',
    characters: [N.yeyo, N.ramiro],
    season: 2,
    tags: ['obras'],
  }),
  bet({
    id: 'tra-bet-charo-anio',
    prompt: 'Apuesta final: ¿cuánto tiempo dijo Charo que iba a estar de presidenta?',
    options: ['Un año', 'Cuatro años', 'Hasta las siguientes obras', 'Toda la vida'],
    correct: 0,
    difficulty: 8,
    category: 'tramas',
    explanation: '"Un año". Estamos en el séptimo.',
    characters: [N.charo],
    tags: ['final', 'junta'],
  }),
  bet({
    id: 'tra-bet-bridas',
    prompt: '¿Con cuántas bridas sujetó Yeyo la antena de la azotea?',
    options: ['Dos', 'Una', 'Cuatro', 'Ninguna, la soldó'],
    correct: 0,
    difficulty: 9,
    category: 'tramas',
    explanation: 'Dos bridas. Y ahí siguen, cumpliendo mejor que muchos acuerdos de junta.',
    characters: [N.yeyo],
    season: 4,
    tags: ['final', 'antena'],
  }),
];
